### ISSUE TITLE
chemical treatment calculation fixes

### ISSUE THREAD

**Issue by hpertaia** [bcgov/invasivesbc#1010]
- [x] edit the herbicide calculation fields to match the attached spreadsheet.   
- [x] move the "application start time" field up into the "Chemical Treatment Information" section (that will get rid of the "treatment information" section entirely".  
- [x] Edit the Invasive Plants section so that you can add more than one species here (only 1 is mandatory though).
- [x] Move the "Chemical Treatment Method" field down to be the first field under the "Herbicide" heading and rename to be "Chemical Application Method". (the user will then choose the chemical application method first and then the Herbicide Type).   Only one Chemical Application Method may be chosen and the field is mandatory.
- [x] Rename the "Herbicide" heading to be "Chemical Treatment Details"
- [x] Create a new field called "Percent area covered" (see the attached spreadsheet for how it's calculated etc).
- [x] update code table for the "Herbicide field" as per the second tab in the attached so that there are two herbicide lists - one for liquid and one for granular - and make sure if a user chooses liquid, they only get to see liquid, and if they choose granular, they only see the granular list.   
- [x] enable more than one herbicide to be chosen 
- [x] If a user chooses tank mix, but only one herbicide is entered, they should get an error message - tank mixes must have at least two herbicides to be complete. 
- [x] ensure More than one invasive plant can be chosen connected to a single set of herbicide data.
- [x] Ensure the table created with the maximum label rates for the herbicides is linked to the Product application rate field so that if a user puts a number in greater than the max allowable rate it says "are you sure?"
- [x] do not allow users to enter the same herbicide twice.  
- [x] when area treated is entered by the user, it can't be greater than the area defined in the polygon.  
- [x] Create a new field called "Calculation Type" with two options (dilution % or product application rate) and use these tool tips for it: Product application rate: the label recommended rate for treatment of this species that was used to mix the treatment solution. In litres per hectare. Dilution % :  the label recommended percent solution used to treat this species that was used to mix the treatment solution. Expressed as the percent of herbicide in the solution. Example: 25% = 25% herbicide concentrate in the treatment solution.  See spreadsheet for where this field should go.

- [x] ENSURE THESE EDITS ARE MADE FOR BOTH THE TERRESTRIAL AND AQUATIC CHEMICAL TREATMENT FORMS
[HerbicideCalcs_v12 oct 27_FINALTODEVS.xlsx](https://github.com/bcgov/invasivesbc/files/7427809/HerbicideCalcs_v12.oct.27_FINALTODEVS.xlsx)

**Comment by CrystalChadburn** [comment]
@hpertaia. @micheal-w-wells and @mikeshasko - here is a summary of what is done in IAPP.  We need InvasivesBC to match this exactly, PLUS add the new functionality for when a granular herbicide is chosen (see main ticket above and contact me when ready to do that part).

**Comment by CrystalChadburn** [comment]
In IAPP, the fields are:
•	Herbicide (user enters)
•	Treatment method – (user enters - affects what things are autocalculated)
•	Area Treated (ha) -this is auto-calculated except when Treatment method is: Wick, Stem injection, Basal Bark, Cut & Insert, or Cut Stump 
Calculation is Amount of Mix Used / Delivery Rate
•	Amount of Mix Used (l) (user enters)
•	Product Application rate (l/ha) (user enters)
•	Dilution (%) (percent of product in the mix) – auto-calculated except when Treatment method is: Wick, Stem injection, Basal Bark, Cut & Insert, or Cut Stump.  Calculation: (Application Rate / Delivery Rate) X 100
•	Delivery Rate (l/ha) (user enters)
•	Tank Mix (check mark) – used to split chemical amounts from a single treatment. in InvasivesBC we will have to figure out how this works.  Rarely used.

Chemical Treatment extract outputs in IAPP, we get a spreadsheet with:
FROM USER ENTERED FIELDS:
o	Area Treated (ha)
o	Amount of Mix Used (l)
o	Application Rate (l/ha) -blank when Dilution (%) is entered
o	Delivery Rate (l/ha) -blank when Dilution (%) is entered
o	Dilution (%)
o	Tank Mix (Y or blank) 

•	Calculated FIELDS 
o	Amount of Undiluted Herbicide Used
	Where Application Rate (l/ha) is entered: Application Rate X Area Treated
	Where Dilution (%) is entered: (Dilution % / 100) X Amount of Mix

**Comment by CrystalChadburn** [comment]
@hpertaia  ok this is now ready for you to action.  If you want to go through the spreadsheet once more with me, let me know.  I've added two tabs since you saw it last to show the overall flow/order of fields and the code table edits required.
