### ISSUE TITLE
Unravel Activity Data

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#1059]
Activity data is a mess.  This was the original gameplan, (with an update on how to deal with computed server side data):

Have activities be a blob.  Have a bunch of computed columns based on blob spatial attributes.  Activity table should look like:
```
row_id, activity_id, version, blob_json_from_device, activity_type, activity_subtype, computedcolum1.....
```
The blob getting sent should look like this:
```
activity_data: {}
activity_type_data: {}
activity_subtype_data: {}
```
The blob getting read should look like this:
```
activity_data: {}
activity_type_data: {}
activity_subtype_data: {}
serverside_computed: {}
```

What we have now looks more like this:
```
{
activity_type:
activity_subtype:
activity_payload: {activity_type, activity_subtype..... form data: { activity_type_data....}
....
more bad nesting and repetition
}
```
There are side effects of other problems that led to this, and other bad workarounds thrown ontop.  Prior to us adding a bunch more forms and especially reporting, we should refactor the PUT, GET, Activity Page, and API_DOCS.json to address this before we're stuck with this mess forever.  There's a bunch of RecordTable code that will have to get scrubbed also.

**Comment by CrystalChadburn** [comment]
Do before the reports

**Comment by dogcomplex** [comment]
Also needs doing:  consolidate the different uses of formatting between API/DB/Web/SQLite side and the "blob"/RJSF/PouchDB/App-JS side.  There are many places where functions are renaming data in different contexts, especially between snake_case and camelCase formats (though sometimes we just name vars differently too...)   Recommend we pick a single format across all contexts (snake_case?) and refactor to that, OR at least make a clear single point where those are mapped from one to the other.

**Comment by dogcomplex** [comment]
Lastly, need a standard on how we will refer to nested keys deep within the blob.  Not hard just - it's better to do that and make standardized functions for accessing/modifying nested references than recreating it everywhere.  "{field1, field2, field3}" as a string?  [field1, field2, field3] as an array in-code?  (Note: this is directly applicable to filters, and to the things that need cleaning in RecordTable, but also good just for current code)  Could also do "field1.field2.field3" or "field1/field2/field3" lol

**Comment by micheal-w-wells** [comment]
as I see it there are 2 parts to this.  one is organizing all of the types in the api doc, which is easily an 8 and Grisha did this.


the next ticket will just be a cleanup to the activity page, to match the activity type, sub type, and data properties.  


thank you @hpertaia for your perseverence on this one.
