### ISSUE TITLE
Glue front-end to back-end for Plan your trip page filters

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#107]

**Comment by micheal-w-wells** [comment]
@NickPhura getting a 400 from your fetch activity endpoint but not seeing any errors on the pod, just rolled with `activity_type` and `activity_subtype` to prove it out.

If you look at #133 can try use the fetch button to reproduce.

Soon as I'm past that I'll wrap this one up, its 99% there.

**Comment by micheal-w-wells** [comment]
ok so as of now you can:

choose activities by type, dates, and a polygon and it will fetch them
