### ISSUE TITLE
create a list of all custom validation rules

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1087]

**Comment by hpertaia** [comment]
### getSlopeAspectBothFlatValidator
Function to validate that in case 'slope' field has 'flat' option selected, 'aspect' field option has to be 'flat' as well (and vice versa)
 - time complexity: O(1)

### getDurationCountAndPlantCountValidation
Function to validate duration of count and plant count fields of biological dispersal form
 - time complexity: O(1)

### getVegTransectPointsPercentCoverValidator
Function to validate total percent value of vegetation transect points percent cover
 - time complexity: O(n^2)

### getJurisdictionPercentValidator
Function to validate that the total percent value of all jurisdictions combined = 100
 - time complexity: O(n)

### getDateAndTimeValidator
Function to validate that the date and time is not in future
 - time complexity: O(1)

### getAreaValidator
Function to validate that the net geo area selected does not exceed the limits specified by business area for various activity types
 - time complexity: O(1)

### getDuplicateInvasivePlantsValidator
Function to validate duplicate invasive plant species on terrestrial plant form
 - time complexity: O(n)

### getTemperatureValidator
Function to validate temperature field on chemical treatment form
 - time complexity: O(1)

### getWindValidator
Function to validate wind fields on chemical treatment forms. If no wind there should be no wind direction. If wind, there must be a wind direction.
 - time complexity: O(1)

### getInvasivePlantsValidator
Function to validate that the value selected for invasive plant in dropdown is one of the plants from the linked record. Ex: cannot create a treatment for a plant that was not observed in linked observation
 - time complexity: O(1)

### getPersonNameNoNumbersValidator
Function to validate that the person field does not contain any numbers
 - time complexity: O(n)

### getHerbicideMixValidation
Function to validate that if the herbicide mix is set to true, there must be 2 or more herbicides chosen
 - time complexity: O(n)

### getHerbicideApplicationRateValidator
Function to validate that the application rate specified for a given herbicide does not exceed the limit based on guideline values.
 - time complexity: O(n)

### determineErrorStateOnTransectPoint
Function used by offset distance validation function to identify and set error on specific field of nested object structure based on transect type
 - time complexity: O(1)

### getTransectOffsetDistanceValidator
Function to validate that the offset distance for a point on a transect line does not exceed the length of the associated transect line
 - time complexity: this one is pretty bad: a lot of loops and mappings and filtering staff.
