### ISSUE TITLE
Short Activity ID needs fixing

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1088]
- [ ] Replace the existing codes for the activity IDs with the ones attached
- [ ] ensure that they are being assigned properly (the current ones were not attaching to records properly)
[InvasivesActivityCodes_Oct14_finalcc.xlsx](https://github.com/bcgov/invasivesbc/files/7354447/InvasivesActivityCodes_Oct14_finalcc.xlsx)

**Comment by mikeshasko** [comment]
![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/99c8563b-d151-4315-9ea3-56ac4c435c0e)
