### ISSUE TITLE
Activity Search Page

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#111]
**Describe the Task**
UI to search and view all records.

- [x] Search filter component
- [x] Pagination component
- [x] Results list page
- [x] Updates to api activity search endpoint to support the above

**Comment by NickPhura** [comment]
There will need to be some updates to the search page, to refine the filters and the columns that we display, etc.  But a basic set of fields/filters are there, and all of the big pieces of code to support the functionality (front/back) are in place.
