### ISSUE TITLE
Map edits from user testing on sept 23

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1142]
- [x] change the icon for changing the colour (currently a paintbrush) to a small colour wheel 
- [x] add a scale bar to the map 

- [x] enable users to save their map preferences for future use (ie. layers they have chosen, colours or symbology they have chosen etc).

**Comment by micheal-w-wells** [comment]
the touch screen drawing tasks remaining are part of the other drawing related work i have in progress, the rest of brian's work here is done so i'm closing it.
