### ISSUE TITLE
Need to increase the ability to zoom in further in mobile

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1144]
- [ ] user testing indicated that the mobile app is not yet able to zoom in far enough to adequately draw a polygon for a record.  

Additional info: the zoom in level is adequate in the web, just not the mobile app.  on the app it greys out the plus icon on the zoom tool and bounces the user back out.

**Comment by micheal-w-wells** [comment]
mike to push up code.

**Comment by micheal-w-wells** [comment]
#1205
