### ISSUE TITLE
Form fixes following sept testing (multiple forms)

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1145]
IN PROGRESS. branch name - issue1145
ALL FORMS (except transects):
- [x] ensure "Adjacent land use" field is able to allow for multiple choices in all forms.
- [x] ensure all forms must have at least one invasive plant chosen to be submitted **(minItems property)**
- [x] Many fields in the have red “this is a required property” message duplicated.  fix so it only shows once.
**this is the RJSF problem try changing oneOf to if-then-else format**
https://json-schema.org/understanding-json-schema/reference/conditionals.html
- [x] For Funding Agency field : When clicking on some agencies from the list it will add that agency plus another agency  Ex. Alberni-Clayoquot RD will also add Capital RD, CCCIPC also adds ISCBC, Central Coast RD also adds ISCBC.  
**this is the problem with multi-select-autocomplete widget**
- [x] For Observation Person(s) field on multiple forms - If you add a person and then remove them the field doesn’t show the “is a required property” message anymore.  Might be the same for all mandatory fields?? can we test and fix this?
- [x] In all forms the date and time are autofilled BUT, if a user tries to change date it won’t let you enter anything and says “should be string” – also once you’ve removed the auto timestamp the field is stuck being empty.   Allow users to override the date and time in the proper format if they need to.
- [x] When making Terrestrial Observation or Chemical Treatment.  Some forms don’t show an errors but remain invalid - are there hidden validation rules?
- [x] for all numerical fields (like Pesticide applicator number or buffer distance when drawing a line) is there a way to have it bring up the number keyboard instead of the letters in your ipad?  No worries if not.
**there is no way to do this.**

Biocontrol Dispersal Monitoring form
- [x] Has two fields for Primary and Secondary Applicator edit to be called Observer Name(s)
- [x]  “Monitoring Organization” should be renamed as employer and linked to the same employer code table as all the rest of the forms.
- [x] There is a Biological Agent Presence field where you can select 1 option from a list of Adults, Larvae, Eggs, Foliar Feeding, Root Feeding, etc. – edit this field so that you can choose multiple selections from the drop down.  
- [ ] @CrystalChadburn to add something else here about the collection history and collection history comments fields and phenology fields after susan reviews.

Biocontrol Collection form
- [x] Start time and stop time says “(mins)” – need a clock to be able to choose the time

Aquatic observation, mechanical and chemical treatment forms:
- [x] Aquatic observation form: Shoreline type requires 100% cover but allows to enter more than 100%.  Limit this to 100%
- [x] Change the name of the "average depth of waterbody" to "maximum depth"
- [ ] @CrystalChadburn to add something here about inflow/outflow fields 

Terrestrial observation form:
- [x] Terrestrial plant observation form has two fields for life stage.

Chemical forms (aquatic and terrestrial)
- [x] when user clicked on a well it showed UTM zone 39 and had wrong coordinates **(latlong reversed)**
- [x] In Terrestrial Chemical Treatment form, the  Application Start Time field can’t enter any info – says “should be string”.  this needs a time clock to enable users to pick a time in the same standardized format as all time fields.

Monitoring forms
- [x] all monitoring forms have two access description fields.  Reduce to 1.

**Comment by sam-warren** [comment]
See https://github.com/bcgov/invasivesbc/commit/1ed94295230b7eee9dbbb7ac951afce6f716f2ee for testing updates
