### ISSUE TITLE
Version 2 of InvasivesBC theme

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#116]
**Describe the Task**
- [ ] @micheal-w-wells to create a button
- [ ] Implement a Dark Theme option for users to allow for useability in the field.

**Comment by victorc-bcgov** [comment]
@micheal-w-wells Reading in the Material Design documentation, there's a note that dark theme is only available (at the moment) on the Android platform. Does this change the priority of this effort?

https://material.io/design/color/dark-theme.html#implementation

**Comment by ZoeSimon** [comment]
> @micheal-w-wells Reading in the Material Design documentation, there's a note that dark theme is only available (at the moment) on the Android platform. Does this change the priority of this effort?
> 
> https://material.io/design/color/dark-theme.html#implementation

@victorchong after conferring with Mike, this one we're going to remove as a priority for now. Can re-visit at a later date.
