### ISSUE TITLE
Test Data Migration

### ISSUE THREAD

**Issue by popkinj** [bcgov/invasivesbc#1174]
There is a current script for loading data. This needs to be extended with the work Brennan did.
- [ ] Extend script
- [ ] Port script to knexJS
- [ ] Test data to only load in Dev and Tst

**Comment by micheal-w-wells** [comment]
going to say its not gonna happen before christmas - parking for now

**Comment by popkinj** [comment]
Yeah... Good call @micheal-w-wells .  The profile of tests I need are constantly changing anyway. Don't think we really need any set case for test data..... Yet at least.
