### ISSUE TITLE
Part III: make drop down / ref data populate in API spec schema

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#119]
**Describe the task**
For the various InvasiveBC dropdowns and related attribute tables we wish to see the following code tables in their respective dropdowns with the default and sort orders in place.
- [ ] convert his tables into db migrations 

**Acceptance Criteria**
1. System codes
- [X] app_role_codes 
2. Business codes
- [x] pest_management_plan
- [x] plant_life_stage_code
- [x] animal_life_stage_code
- [x] plant_health_code
- [x] plant_seed_stage_code
- [x] animal_behavior_code
- [x] bioagent_maturity_status_code
- [x] biological_agent_stage_code
- [x] biological_agent_presence_code
- [x] classified_area_code
- [x] proposed_treatment_code
- [x] observation_type_code
- [x] observation_geometry_code
- [x] specific_use_code
- [x] aspect_code
- [x] invasive_plant_density_code
- [x] slope_code
- [x] invasive_plant_distribution_code
- [x] mechanical_disposal_code
- [x] mechanical_method_code
- [x] root_removal_code
- [x] soil_disturbance_code
- [x] treatment_issues_code
- [x] soil_texture_code
- [x] chemical_method_code
- [x] efficacy_code
- [x] liquid_herbicide_code
- [x] granule_herbicide_code
- [x] invasive_plant_code
- [x] invasive_animal_code
- [x] biological_agent_code
- [x] invasive_species_agency_code
- [x] jurisdiction_code
- [x] pesticide_employer_code

Steps:
- [X] make migrations and seeds work with Roland's structure (done as per ticket #73)
- [x] create a mechanism to read the seed data from csv files
- [x] convert Mike Shasko's spreadsheets into csv files (30 files)

**Additional Context**
- [ ] knex.raw and using the postgres csv loader: https://www.postgresqltutorial.com/import-csv-file-into-posgresql-table/

**Comment by anissa-agahchen** [comment]
27 tables in, parking this ticket for now ... @mikeshasko is reviewing the content.

**Comment by anissa-agahchen** [comment]
As per conversation with @shasko, removed table ' pesticide_employee_certificate_code` from the list of tables to add to the code tables.
