### ISSUE TITLE
Metabase question: Summarize all chemical treatments within a Pest Management Plan area

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1207]
- [ ] Do not action until #1010    is complete.
- [ ] Upload the Pest Management Plan boundaries (attached)
- [ ] enable users to choose a timeframe and a list of multiple jurisdictions, and a boundary area to summarize chemical treatments for all species
- [ ] output should provide a summary of all companies and their service licences that applied herbicide AND summarize the Pesticide Product Name, Active Ingredient, PCP Registration Number, Quantity Used (kg), size of treated area (Ha) and List of methods of application - see attached for example of what people have to fill out to report annually to MOE.
- [ ] should also provide an output in excel of all treatment records for the query (so we can review and fix any errors before we submit the report to MOE)[https://app.zenhub.com/files/296689811/f6a30be9-29cb-4ea8-b2fd-1aea2daa3951/download](https://app.zenhub.com/files/296689811/f6a30be9-29cb-4ea8-b2fd-1aea2daa3951/download)

**Comment by popkinj** [comment]
Yeah... The link is broken @CrystalChadburn :(
