### ISSUE TITLE
Admin Activity - Change user Role

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#121]
As an Admin User I wish to be able to affect administrative tasks specific to changing the roles of an existing user,

See screen grabs in the comments.

**This issue was noted in #316 as requiring it's own ticket.**

**Acceptance Criteria**
- [ ] Given a multi-selected record, this is the action to delete, undelete and change access role.
- [ ] Admin tab available to "admin" users only on web
- [ ] Allow the admin tab to function only on the web portal
- [ ] The landing page should list out all the users in the system
- [ ] Include a button (Actions) by each to review their current status
- [ ] Provide a dropdown of the roles (Admin, Manager, Data Editor)
- [ ] Provide a slider to de-activate a user 

Granted that any user can access the system at this time with an IDIR/BCeID we need to be able to disable a user.

**Comment by ZoeSimon** [comment]
Addressed through #315 #316 & #317. Moved to Parking Lot for now.

**Comment by ZoeSimon** [comment]
@mikeshasko Need clarity on why this page is needed

**Comment by ghost** [comment]
The Admin / Roles page clips from the old version:


![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/35bc96d9-8bbc-417d-9971-e797e5835aa1)

![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/22c5c02c-bcca-42ae-8cf3-a22126b76e4a)

![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/7eb78421-879a-4484-8f88-c97915c804d3)
