### ISSUE TITLE
New Terrestrial Animal Observation Form

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1244]
- [x] replace the existing terrestrial animal observation.,treatment and monitoring forms with the content in the attached spreadsheet.
- [x] replace the existing terrestrial animal species list code table with the one attached to this ticket.  (use what is attached for now, we are working on the missing codes and i will make a new ticket to update the code table when it is ready)
- [x] ensure the name of the form is at the top similar to what we did for plants.

[https://app.zenhub.com/files/296689811/81c0575e-4ab3-470b-9561-0e24eb1d7c10/download](https://app.zenhub.com/files/296689811/81c0575e-4ab3-470b-9561-0e24eb1d7c10/download)[https://app.zenhub.com/files/296689811/94b597cf-9926-45ae-9237-e06761d48a94/download](https://app.zenhub.com/files/296689811/94b597cf-9926-45ae-9237-e06761d48a94/download)

**Comment by CrystalChadburn** [comment]
@hpertaia and @sam-warren I have a meeting with the animal folks thursday at 1pm so if there is anyway to get this first updated version of the terrestrial animal forms done by then that would be amazing!

**Comment by sam-warren** [comment]
@CrystalChadburn I'll do my best to squeeze it in before then :)
