### ISSUE TITLE
Moving Inspect App to Openshift 4

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#127]
**Describe the Task**
Moving Inspect App to Openshift 4

Related to #113
#144 Needs to be executed first

- [x] Update all code to refer to the new Project on OCP4 - for Lucy
- [x] Update Lucy Pipeline to refer to OCP4 and new server locations
- [x] Consolidate NSP and External network code in the repository
- [x] Run Lucy Pipeline
- [x] Verify Lucy Results

**Comment by rstens** [comment]
Still adding tools and tests.
