### ISSUE TITLE
Update front-end to work with code tables

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#128]
**Describe the Task**
Update front-end to work with code tables

@anissa-agahchen to fill out specifics

**Comment by NickPhura** [comment]
Specifically regarding the form drop-downs:

The front-end shouldn't need any changes (assuming I'm not forgetting anything).  All of the code tables for the forms are populated into the spec before it it sent from the API.  

The current code that populates those code tables is here: https://github.com/bcgov/lucy-web/blob/dev/api-mobile/src/utils/api-doc-security-filter.ts

Currently it leverages a couple of `x-blah` tags that are in the spec to determine which code tables/values to pull in.  
```
          "species_agency_code": {
            "type": "string",
            "title": "Agency",
            "x-enum-code": {
              "x-enum-code-set-name": "species_agency_code",
              "x-enum-code-value": "species_agency_code",
              "x-enum-code-name": "description"
            }
          },
```

That overall mechanism should still work, but the actual `x-blah` tags and the `api-doc-security-filter.ts` code will need updating to account for the new code-table model.

**Comment by sdevalapurkar** [comment]
I think this has been taken care of with https://github.com/bcgov/invasivesbc/pull/187 right @NickPhura unless there are additional requirements
