### ISSUE TITLE
Layer picker and magnifying glass finalization

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1280]
[Final list of layers_for DEVs_Nov26.xlsx](https://github.com/bcgov/invasivesbc/files/7610194/Final.list.of.layers_for.DEVs_Nov26.xlsx)
- [x] make "just this point" the default for the magnifying glass (rather than within radius)

- [x] change the magnifying glass icon to binoculars or the "info" i button.
- [ ] add option in layer picker to upload their own kml/kmz including being able to see the metadata (CONFIRMED THE NEED - WORK WITH MIKE)
- [x] update the layer picker to look like the mock up attached
- [x] @CrystalChadburn will attach the list of which layer will be under the new categories in the attached mock up.
[DESIRED LAYER PICKER MOCK UP.docx](https://github.com/bcgov/invasivesbc/files/7515660/DESIRED.LAYER.PICKER.MOCK.UP.docx)

- [x] update layer picker so that every layer has it's own colour and transparency settings (not each category of layers as shown currently).
- [x] update layer picker so that when you choose the colour wheel icon, you are given the actual colour wheel and not a number, as well as a slider for transparency for that particular layer.
- [x] Allow users to click and hold and slide the layers up or down to build what order they will show on the map (currently built for the categories of layers, but should be for individual layers ideally if that's not too hard).
- [x] update layer picker so that the layer modes is hidden to the user, they should not have to understand or choose which type they need depending on whether they are online or offline etc.  (solution is to hide this in prod and the app.)
- [x] Fix the jurisdiction layer in the administrative boundary category to make it work, and ensure the styling comes along with it to show different colours.

**Comment by CrystalChadburn** [comment]
@bburciaga and @micheal-w-wells - final list of layers for the layer picker is attached.  

Thanks!

**Comment by micheal-w-wells** [comment]
let's close this one, brian has done 99% of it all that's left is the KML for me
