### ISSUE TITLE
GPS tracker fix (to draw the polygon for your record)

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1289]
- [ ] ensure that the GPS on the ipad is communicating accurately with InvasivesBC
- [ ] enable the "track polygon" using the GPS on the forms to work (ask @micheal-w-wells  how to do this)
ONLY IF DONE IN ONE DAY.

**Comment by micheal-w-wells** [comment]
@plasticviking if you have throughput you can snag this one, I'm out of here until Tues so won't have time.  Check out the capacitor geolocation plugin that handles background gps and look at swapping it out.   take a peek at the pr that was merged / reverted for the branch with the most complete code.
