### ISSUE TITLE
Herbicide Report

### ISSUE THREAD

**Issue by popkinj** [bcgov/invasivesbc#1352]
Attached is an example of what we have to submit each year for herbicide reporting in the exact format in the attached form.

I would like users to be able to use meta see to querying within a PMP boundary (or user uploaded kml boundary), narrow down by one or more jurisdictions and a date Range, and then have the summary table outputs show us the area of each chemical as you see on the attached form.  Also, you will see on the attached form that we have to list all the service licence numbers so the user will have to sort the query by those numbers as well.

Note this is just one type of chemical treatment query that uses all species but we also want the species drop down in the chemical query as people will often search for one or more specific species too.

NOTE: Use the jurisdiction field from the forms, do not spatially re-calculate it.

This is the form that I tried linking to the ticket but it was no longer working.
[https://app.zenhub.com/files/296689811/bf056055-ef50-40bb-8018-5712120a6c88/download](https://app.zenhub.com/files/296689811/bf056055-ef50-40bb-8018-5712120a6c88/download)

**Comment by CrystalChadburn** [comment]
closing this as we are planning to use the general chemical query that brennan webster.
