### ISSUE TITLE
Android tasks

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1359]
Feb 7 update - passing this onto Rob.
- [ ] get app links working - or at least one link that goes to app on login
- [ ] other build issues if there are any - ideally get android gh action working again

**Comment by CrystalChadburn** [comment]
@plasticviking so my understanding is you have been able to get the app to stand up on an android now but we still need to sort through getting the app into the android store, is that correct?  Please add details into the comments of this ticket.

**Comment by plasticviking** [comment]
@CrystalChadburn Yes, that's correct. I've got the android app working and building both on a simulator and a physical tablet (old Lenovo I had collecting dust). It seems to work pretty well.

I think we need another ticket for the process of getting it into the store. Is there a government process for this similar to the IOS signing/publishing process? https://mss.developer.gov.bc.ca/ ? Do we have a Google Store account?
