### ISSUE TITLE
Fix the activity page and how it talks to the backend

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1360]
- [ ] when a user edits a form, or makes a change, it needs to purge older versions instead of duplicating/keeping.

- [ ] clean up the format of the data when it is submitted.

**Comment by micheal-w-wells** [comment]
we weren't able to tackle this one prior to moving on reports, so it will have to happen when the other must haves are done.  not a showstopper.

**Comment by micheal-w-wells** [comment]
the issue of way too many versions for user edits is solved - the format of the data is pretty well locked down now that there are reports built on it so parking this one indefinitely
