### ISSUE TITLE
Explore why metabase crashes when extracting less than 1Million records to csv

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1365]
- Turn the knobs in the back end to enable large data sets to be exported in metabase, currently we get the "Gateway timeout" page.

**Comment by CrystalChadburn** [comment]
@plasticviking any update on this?  Do we need to check whether this is still actually happening?

**Comment by plasticviking** [comment]
@CrystalChadburn This error actually comes from Openshift, not Metabase, and it can also depend on the download bandwidth of the client. I've adjusted the timeout on the route up to 10 minutes and cannot reproduce it. Could use another set of eyes to verify.

We will need to replicate this configuration change (add annotation `haproxy.router.openshift.io/timeout: 10m`) in test and prod if it is confirmed as working.

**Comment by CrystalChadburn** [comment]
@plasticviking  Brennan and another one of our staff tested this and it crashed with 530 000 rows

**Comment by CrystalChadburn** [comment]
@plasticviking Brennan tested this and it works!  I'll close the ticket now.  Great work!
