### ISSUE TITLE
Flatten form data into tables for use in metabase

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1366]
This is needed to make the InvasivesBC queries look similar to the IAPP queries that Brennan created to allow users to filter the dataset down using the fields in the table view, and then go to the visualization page to see the results and further query down by a spatial boundary.

Needs to be done for all forms:
- terrestrial observation
- aquatic observation
- terrestrial chemical treatment
- aquatic chemical treatment
- terrestrial mechanical treatment
- aquatic mechanical treatment
- Biocontrol, mechanical and chemical monitoring (3 forms)
- Biocontrol collection, release and dispersal monitoring

As of Jan 17th, still to do:
- [ ] link the metabase tables to the proper column in the code tables (ie. to the jurisdiction name versus the jurisdiction shortform code
- [ ] Separate the arrays so that they can show up as individual records
- [ ] connect the work Jamie has completed with the tables brennan has made

**Comment by micheal-w-wells** [comment]
This just might be the biggest ticket we ever made.  Brennan did TONS of work on this, and is more or less on to the sticker requirements (spatial fields, array fields, etc).  Will make him another ticket so we don't drag this one on as if nothing happened.

**Comment by micheal-w-wells** [comment]
InvasivesBC Reporting (flattening) v3
- [ ] all forms have a report (many WIP)
- [ ] all array fields done
- [ ] all spatial fields done
- [ ] Jamie and Brennan regroup on overlapping work
