### ISSUE TITLE
Monitoring Form Edits 

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1397]
- [x] insert a new field into mechanical treatment monitoring form called "Aquatic Invasive Plant" that uses the aquatic_invasive_plant_code and change the name of the current invasive plant field to "Terrestrial Invasive Plant".  This change is required because there is only one monitoring form for both aquatic and terrestrial mechanical treatments.

- [x]  insert a new field into chemical treatment monitoring form called "Aquatic Invasive Plant" that uses the aquatic_invasive_plant_code and change the name of the current invasive plant field to "Terrestrial Invasive Plant".  This change is required because there is only one monitoring form for both aquatic and terrestrial chemical treatments.

- [x] make sure the UTM fields in both chemical and mechanical monitoring forms are in this order: zone, easting, northing.

- [x] Change the title of the mechanical  monitoring forms to be ‘Activity Monitoring Mechanical Plant’ (currently it's called chemical)

- [x] The biocontrol RELEASE monitoring form is missing a field that that ties it to a biocontrol release form (similar to what we have for chemical and mechanical treatment monitoring).  Add a new field.
- [x] add a new optional field in both chemical and mechanical monitoring forms called "Treatment Pass" with a drop down with First, Second or Unknown as options, and default to blank.  Help text should be: "Indicate whether you are monitoring the first or second treatment pass of the calendar year, if known".
- [x] add a new mandatory yes/no toggle that says "Evidence of treatment?" to both chemical and mechanical monitoring forms.
- [x] add a new mandatory multi-select drop down field to the chemical and mechanical treatment form called "Invasive Plants on site" that links to a new code table called monitoring_evidence_code.  Allow users to choose one or more.  Include help text that says "Choose one or more option to indicate whether target invasive plants are still found on site following the treatment."
- [x] edit the name of "Efficacy Rating" on both mechanical and chemical treatment MONITORING form to be "Treatment Efficacy Rating" and add help text that says "Choose the efficacy of the treatment for the area that was treated."
- [x] add a new mandatory field to both the chemical and mechanical treatment forms called "Management Efficacy Rating" with the help text that says "Choose the efficacy rating indicating the mortality of all the target species found on the site, including those that were not treated. Eg: 50% of plants on the site have evidence of treatment = Efficacy of 5.  Link to new code table called management_efficacy_code 

- [x] Change the name of "monitoring details" to be "Efficacy Comments", make it optional, and add help text to the Efficacy comments for both mechanical and chemical treatment monitoring form that says: "Provide any other observations of the treatment that was completed."
- [x] update the help text on the Comments field for the mechanical monitoring form only to say "Add any additional relevant information about the efficacy of the treatment including missed plants, seeds left on site, etc.".
- [x] test the linkage of these monitoring forms to chemical, biological release and mechanical treatment functionality (reminder need to be able to manually enter the ID from the treatment form at minimum... plus used to have the functionality to be able to click on the treatment record and it automatically enter that field with the treatment ID.)
- [x] Find a solution for this issue: Because a monitoring record is linked to the treatment record, it should use the geometry from the treatment record rather than creating a separate geometry ideally.

**Comment by hpertaia** [comment]
We will need to merge api_doc_refactor before tackling this.

**Comment by CrystalChadburn** [comment]
@micheal-w-wells can you please have a look at the last bullet here re linking the monitoring forms to their treatments.  @hpertaia i added another easy one for you here too.

**Comment by CrystalChadburn** [comment]
@hpertaia added a new field for the monitoring forms into this ticket

**Comment by CrystalChadburn** [comment]
@hpertaia  sorry moved them over to #1519 which is ready for you

**Comment by CrystalChadburn** [comment]
Need to complete #1638 and get the chemical treatment form to be able to get to submit first (sam's service licence stuff done for ministry users and then test) and then we can do this.
