### ISSUE TITLE
user access roles 

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1413]
- [x] confirm that ONLY administrator users will be able to edit other people records.  Otherwise only the person who created the record should be able to edit them. 
- [x] Users should be able to view activities from ALL users regardless of roles.

**Comment by sam-warren** [comment]
Had to re-think current implementation of users seeing only roles they have access to for security and efficiency purposes. Working on designing a better solution, half-implemented and in testing. Approx. 4hrs left on this one.
