### ISSUE TITLE
Compare updated plan my trip page with user feedback

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1414]
- [ ] 
- [ ]
- [ ] 
- [ ] keep the metabase query 
- [ ] keep the kml query

Plan My Trip Old User feedback:

-	I found the whole page difficult to scroll around and go through the steps (when the steps are expanded, the sections take up the whole screen
-	Could you include a search bar on this map so you can zoom in quickly to an area (e.g. Squamish). The basemap with no labels makes it difficult to know where you are…. Place names might help a bit!?
o	Step 1 – Name your trip (couldn’t find a field to edit?)
o	Step 2 – easy to use, but requires you to scroll back up – could you place the map after Step 2 in the instructions?
o	Step 3 – unclear how this would work? Difficult to test right now! Does this just grab the records from within the polygon area?
	Date fields, include a button to go back years, not just months – Ah - I see you can do that by clicking on the yr…. just not super intuitive.
	When you’re are Step3, you can’t scroll down far enough to click on the ‘I’m done’ button (unless you move the scrollbar in the opposite direction – up to go down…. weird!)
o	Step 4 and 5 (metabase) will need some more explaining – too hard to test right now. Scroll bar issue again.
o	Step 6 – would be good to see a spinny widget or some other graphic to let you know its processing. It was quite quick to cache most of the Squamish district! I will be keen to see if that changes when you mess with the zoom resolution.
o	There is no ‘good to go’ message or way of knowing that the next step is to ‘start your field day’!
-	Cached records:
o	Says:
	Cached Activities ‘no cached records to display’ – makes sense.
-	My records:
o	Tried to add a few different forms – I can see the map, but can’t scroll down on any of the pages!!
o	Once I am on a form, I can’t select anything (i.e the menu button doesn’t respond, and I have to close and re-open the app.)
o	App crashed a few times too…..
-	Maps:
o	Layers list takes a while to load
o	What will be visible in this view once IAPP is loaded in, and new observations and other records have been entered?
o	Same zoom issue as webs version – can’t zoom in close enough
-	Current Activity
o	Freezes and can’t navigate around anymore (can’t even minimise the menu)

**Comment by micheal-w-wells** [comment]
Going to be a lot of changes here - most feedback not going to be relevant.  going to simplify this page quite a bit.
