### ISSUE TITLE
Securing Metabase

### ISSUE THREAD

**Issue by popkinj** [bcgov/invasivesbc#1421]
Metabase has it's own authentication system. There has been some work down by other teams to secure Metabase with IDIR.
Here is a sample Metabase config supplied by Roland Stens that integrates IDIR accounts.
![metabase-idir-config.png](https://images.zenhubusercontent.com/5f1a0071df06d9e9ef77161e/1c4486b7-dc77-4559-8ccb-e644eb06ff00)

Currently, I haven't seen this in use. So I don't know how IDIR users log in, ie If they get redirected to the CLP (Common Login Page) or use the Metabase login form.

It was noted that all access restrictions are configured within Metabase.

**Comment by CrystalChadburn** [comment]
@plasticviking could you please provide a detailed update on where we are at with this ticket in the comments here please.  We can discuss in detail on tuesday's sprint planning as well.  Thanks!

**Comment by plasticviking** [comment]
@CrystalChadburn I've got LDAP authentication working locally, and have a little bit more configuration to do to get it running in dev. Our app needs a service account for bcgov IDIR to authenticate. I am chasing it down and will let you know if I need help expediting it.

I'm planning to temporarily stand up a second metabase instance within our dev environment to allow experimentation with this without disrupting the existing instance.

I've created a set of scripts that execute periodically (as a CronJob) that can keep Metabase Groups (permission sets) in sync with application user roles.

**Comment by CrystalChadburn** [comment]
Ideal solution is that a user will get an email when they have their InvasivesBC access approved that gives them the website and their log in info for metabase with a little blurb that outlines what metabase is.

**Comment by CrystalChadburn** [comment]
@plasticviking Hi Rob, Can you please provide another update on this ticket and where we are at with options to implement using the free version of metabase.

**Comment by CrystalChadburn** [comment]
do table level access only

**Comment by CrystalChadburn** [comment]
@plasticviking i sent you an email on this as well on April 1, 10am PST.  Attaching that same spreadsheet here to the ticket to show the 2 groupings of users to assign to the tables - Master administrators need to see all tables, and everyone else needs to see only the list of tables included in the attached spreadsheet.  
[Access level content for devs_2022.xlsx](https://github.com/bcgov/invasivesbc/files/8399705/Access.level.content.for.devs_2022.xlsx)
