### ISSUE TITLE
Filling Table Columns

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#147]
**Describe the Task**
Performing spatial overlays on all record entries of the `activity_incoming_data` table to populate meta data columns. Related to ticket #873.

## Filling table columns
- [x] ownership
- [x] biogeoclimatic_zones
- [x] regional_districts
- [x] flnro_districts
- [x] moti_districts
- [x] UTM Zone
- [x] IPMA _Internal dataset_
- [x] regional_invasive_species_organization_areas _Internal dataset_

**Comment by popkinj** [comment]
Just realized that many of these columns don't exist in the table. Working on a migration to add them all.
