### ISSUE TITLE
InvasivesBC Reporting (flattening) v3

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#1503]
InvasivesBC Reporting (flattening) v3
- [x] all forms have a report (many WIP)
- [x] all array fields done

_Originally posted by @micheal-w-wells in https://github.com/bcgov/invasivesbc/issues/1366#issuecomment-1020568712_

**Comment by CrystalChadburn** [comment]
@micheal-w-wells this is complete but needs test data before closing.
