### ISSUE TITLE
Metabase access solution

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1509]
Ideal solution is that a user will get an email when they have their InvasivesBC access approved that gives them the website and their log in info for metabase with a little blurb that outlines what metabase is.

Related to #1421

**Comment by CrystalChadburn** [comment]
@plasticviking could you please provide a detailed update on where we are at with this ticket in the comments here please. We can discuss in detail on tuesday's sprint planning as well. Thanks!

**Comment by plasticviking** [comment]
@CrystalChadburn This is the same as #1421
