### ISSUE TITLE
Terrestrial and aquatic chemical treatment form edits 

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1514]
Terrestrial chemical treatment form:
- [x] change name of "unlisted dropdown" to "PMP # not in dropdown" and add helptext that says "Include a PMP number here if it is not available on the drop down in the "Pest Management Plan" field.
- [x]  Feb 28 I unchecked this as it still isn't working for me.  issue with granular calculation.  Users were unable to test granular with either percent or product application rate, errors were given but scenarios should have been allowed.

- [x] updated feb 28: Add the word Litres into the field name undiluted herbicide used in the calculation results object.  This field will always be in Litres, with liquid or granular so we can add it into the name of the field.  Also add help text to the calculation results object that says : "When either or both liquid or granular herbicide is chosen, the units for undiluted product used is in L.itres." Do this for both aquatic and terrestrial please.
- [x] Create a new object immediately before the chemical treatment information called "Pest injury threshold determination".  Have two checkboxes in this object (mandatory to choose one or the other).  First choice is: A full survey was completed prior to herbicide application. The survey determined that injury thresholds had been met to fulfill IPM obligations.  The second checkbox is: No threshold determination was completed. Help text for this object should be "Required field under the BC Integrated Pest Management Regulation when working under a license or authorization".
- [x] Add a new mandatory field within the treatment details object (or near it) called “Precautionary statement” linked to precautionary_statement_code for its drop down. Help text for this object should be "Required field under the BC Integrated Pest Management Regulation when working under a license or authorization".
- [x] Add a new mandatory checkbox that autofills to no called “NTZ reduction” and if you choose it as yes, you get a warning that says “Are you sure?  Only the PMP or permit holder may approve an NTZ reduction on public lands”, and then if the users proceeds with yes, a new mandatory field pops up that says “Rationale for NTZ reduction”. Help text for this object should be "Required field under the BC Integrated Pest Management Regulation when working under a license or authorization".
- [x] Choosing a direct application method (cut stump, injection) does NOT limit you to Dilution as a calculation type. But it does tell you that its an Invalid Scenario.  
 - [x] Tank Mix help button doesn’t work  
- [x] add a new optional user filled checkbox within the well information object that says "Additional/unmapped wells or water license intakes within 30m."   Add help text for this field that says "Check this box as an indicator that there are wells or water licenses that will need to be considered if chemical treatment is planned for this area in the future.  If unknown, leave unchecked.  Additional information can be added into the comments (no names or addresses).".
- [x] for the well autofill tool, it needs to be able to populate with more than one well if more than one is found.  Also, is there a way to hide the fields or show "no wells found" if nothing comes up? @CrystalChadburn to confirm that it is working still.
- [x] It appear that the json is not going into the tables from data entered into the form (Brennan confirmed this).  

Aquatic chemical treatment form:
- [x] change name of "unlisted dropdown" to "PMP # not in dropdown" and add helptext that says "Include a PMP number here if it is not available on the drop down in the "Pest Management Plan" field.
- [x] change the code table for the invasive plant field so it points to the aquatic invasive plant code, not the terrestrial list.
- [x]  Feb 28 I unchecked this as it still isn't working for me. issue with granular calculation.  Users were unable to test granular with either percent or product application rate, errors were given but scenarios should have been allowed.
- [x]  Create a new object immediately before the chemical treatment information called "Pest injury threshold determination". Have two checkboxes in this object (mandatory to choose one or the other). First choice is: A full survey was completed prior to herbicide application. The survey determined that injury thresholds had been met to fulfill IPM obligations. The second checkbox is: No threshold determination was completed. Help text for this object should be "Required field under the BC Integrated Pest Management Regulation when working under a license or authorization".
- [x] Add a new mandatory field within the treatment details object (or near it) called “Precautionary statement” linked to precautionary_statement_code for its drop down.  Help text for this object should be "Required field under the BC Integrated Pest Management Regulation when working under a license or authorization".
- [x] Add a new mandatory checkbox that autofills to no called “NTZ reduction” and if you choose it as yes, you get a warning that says “Are you sure? Only the PMP or permit holder may approve an NTZ reduction on public lands”, and then if the users proceeds with yes, a new mandatory field pops up that says “Rationale for NTZ reduction”.  Help text for this object should be "Required field under the BC Integrated Pest Management Regulation when working under a license or authorization".
- [x] Choosing a direct application method (cut stump, injection) does NOT limit you to Dilution as a calculation type. But it does tell you that its an Invalid Scenario.  
- [x] Tank Mix help button doesn’t work  
- [x] It appear that the json is not going into the tables from data entered into the form (Brennan confirmed this)
- [x] remove shoreline types object

**Comment by hpertaia** [comment]
Unable to do the warning dialog for NTZ reduction. Made it so that the warning is displayed under the second field.

**Comment by hpertaia** [comment]
Well Information is a read-only array that auto-populates now. Also, it is used in other activities. I've put the new Additional/unmapped wells field under the treatment information section for now. Is this alright? @CrystalChadburn

**Comment by hpertaia** [comment]
- [ ] tester tried 1 plant tank mix with 1 liquid and 1 granular. Said it worked but the amount of undiluted herbicide is in grams but doesn't show the units. Add grams as the unit.

**this one is problematic**

**Comment by CrystalChadburn** [comment]
Confirmed granular still not working with any scenario.  Also, we as discussed, we need a solution under the calculation results object to show the units for Amount of undiluted herbicide used.  We have the units for the area treated written right in the unit name, so could do that but it would need to say grams for granular and L for liquid and when both are used, it needs to show which is which.  The work around is to add help text to the calculation object that says "When liquid herbicide is chosen, the units for undiluted product used is L.  When granular herbicides are chosen, the units of undiluted herbicide used is in grams. "

![image](https://user-images.githubusercontent.com/82186073/156028267-4aa4a11a-7bfa-4c25-b8d6-e8b77ecd8ea4.png)

**Comment by CrystalChadburn** [comment]
talk to crystal before actioning more on this.
