### ISSUE TITLE
auto-suggestion for jurisdiction no longer showing up

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1516]
User testing has indicated that we are no longer getting the stars beside the jurisdictions to indicate it is autosuggesting it.

- [x] fix the issue
- [x] test every form to make sure it's working

**Comment by CrystalChadburn** [comment]
@micheal-w-wells and @hpertaia  I have reopened this ticket as I do not see auto-suggestion working in dev.  Please confirm and show me this working before we close it again.  Thanks! :)

**Comment by hpertaia** [comment]
This is fixed. Note: Jurisdictions are working only for Vancouver island.
