### ISSUE TITLE
UTM manual entry fixes 

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#1543]
- [x] update the order of the fields when a user enters their UTMs manually instead of via the map so it asks for "ZONE", then "EASTING", then "NORTHING" (UTMs need to always be in this order "ZEN")
- [x] when a user enters a UTM manually, the map does not respond and zoom into the area.  Please make it do this.

RELATED COMMENTS FROM CLARE:
o	Point – need to clarify is the UTM/lat long location the bottom tip of the point marker, or the white dot in the centre of the icon?
	Looks like it creates a circle (about the size of a car) – this might be difficult to define a precise (single plant) location
	Recording a point, has the same symbol as the location marker – suggest these be different (even a different colour would be good)
	We have been recording single plants to the 0.25m (e.g. a single stem of knotweed is sometimes less than 1m2)… Can we set the minimum to be 0.25m2 rather than 1m2? This will be helpful when you are trying to show efficacy when you’re a few years into repeated treatments, and the gains are small (after the big reduction in area after the 1st treatment)
	Also, can you set the area to be editable? E.g. not every point will be 1m2 in area (it is greyed out for me)

**Comment by CrystalChadburn** [comment]
@micheal-w-wells  I added a couple points onto this which will make it a bit more work to complete.  Let's discuss when you get to this.

**Comment by micheal-w-wells** [comment]
- [ ] When a user enters a UTMs manually, it defaults to the area being 1 m2 and a point, or user can drop a polygon that starts as a square, with the north east corner being the entered utm.
