### ISSUE TITLE
Forms: Create Terrestrial Animal Observation

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#156]
**Describe the Task**
Ensuring the form content and behaviour is accurate for Creating a Terrestrial Animal Observation.

**Acceptance Criteria**
- [x] Activity status should be removed, this should not be editable or viewable as a dropdown to the user. 
- [x] Photo toggle should be removed from form, photo option available at bottom in photo section.
- [x] "Created date on device"/"Updated date on device" do not need to be visible in form. 
- [x] "Paper file" should say "Paper File I.D."
- [x] Observation time & date should be auto-filled, but should be editable.
- [ ] Time should reflect a 24 hr clock, not AM/PM.
- [x] "Type" should be removed as this reflects type of geometry that the user has selected, and this should  be auto-filled and not visible to the user in the front end. 
- [x] "Area" should be auto-filled based on the geometry the user has selected, and should be visible to the user but NOT editable.
- [ ] Order of fields needs to be addressed once we have confirmation of how the form will be laid out, confirm with Mike Shasko.

**Comment by sdevalapurkar** [comment]
These tasks have been completed as part of https://github.com/bcgov/invasivesbc/pull/182 😄

**Comment by ZoeSimon** [comment]
@mikeshasko Please review
