### ISSUE TITLE
BUG: still able to enter UTMs outside of BC

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1573]
User testing revealed that the system will still let you place records/UTMs outside of BC.  Brennan tested this and confirmed that the system will corrects you if you get too far away from the bc border but you can definitely place points outside bc.

- [x] records/UTMs are restricted to ONLY within BC.

**Comment by CrystalChadburn** [comment]
@micheal-w-wells is this related to the fix you did to enable haida gwaii to be included?  Please let me know how much work this is, could be post-launch if needed.

**Comment by hpertaia** [comment]
@CrystalChadburn I did that fix. Just redrew the bc geometry then, but it wasn't too precise. It is an easy fix, just have to get that BC geometry from @popkinj.
