### ISSUE TITLE
Integrate photos in photo container on edit activity page

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#16]
- [x] Integrate photos in photo container on edit activity page
- [ ] Make photos associate to activity record in local database

_Originally posted by @ZoeSimon in https://github.com/bcgov/invasivesbc/issues/14#issuecomment-697990473_

**Comment by micheal-w-wells** [comment]
dupe

**Comment by ZoeSimon** [comment]
Duplicate - captured in ticket #907
