### ISSUE TITLE
MapProxy server

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#161]
**Describe the Task**
Implementing MapProxy server that Jamie has identified below.

> I'm glad I had another look at this one @ZoeSimon .

> Turns out the two existing offline plugins for Leaflet; [offline](https://github.com/allartk/leaflet.offline) and the [pouchdb one](https://github.com/MazeMap/Leaflet.TileLayer.PouchDBCached) only support TMS services... Which are typically used in Basemap layers. Like the BCGov and ESRI basemaps.

> So I think we have two options
> 1. Enhance our existing plugin to also accept WMS layers
> 2. Spin up a [MapProxy](https://mapproxy.org/) server that will do the conversion WMS->TMS for us.

> I'm leaning towards the later of the two options because we would gain some advantages:
> 1. Faster layers
> 2. Layer level security
> 3. We won't have to figure out someone else's plugin code.

_Originally posted by @popkinj in https://github.com/bcgov/invasivesbc/issues/124#issuecomment-721372459_

**Comment by micheal-w-wells** [comment]
we have a map proxy instance in the invasives namespace if that helps

**Comment by popkinj** [comment]
That may do the job @micheal-w-wells
