### ISSUE TITLE
IAPP Migration: Surveys

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#163]
**Describe the Task**
Migration of IAPP "surveys" into InvasivesBC app

**Acceptance Criteria**
- [x] Load data
- [x] Make UI

**Notes**

The Survey data is to be keyed to the Site data on the SiteID variable.

For every SiteID there will be at least one survey and up to 10 or more.
But in some cases a site may not have a survey as the surveys might have been deleted or merged at some point.
Do not display any site that does not have  survey.

The order of the survey data is to be maintained as in the survey list. They data is sorted by species with the surveys on each listed from newest to oldest.

The comment field in the survey has been truncated to 300 characters.

3 jurisdiction and jurisdiction percentages can be displayed within the site list as those are replicated on each survey per site.

Additional survey variables can be included in the survey display should space and layout warrant their inclusion.

Samples

- SiteID, SurveyID, SurveyDate, EstArea, WeedsFound, MapCode, CommonName, Species, Genus, SurveyAgency, Jur1, Jur1pct, Jur2, Jur2pct, Jur3, Jur3pct, EmployerCode, Density, Distribution, SurveyType, PaperFileID, Comment

- 352565,782342,2020-11-06,0.0010,Y,BO,"Bohemian knotweed   ",FALL,BOH,FVIP,MOP ,100,    ,000,    ,000,200817,"2: Med (2-5 plants/m2)   ","5: a few patches or clumps              ",O: Operational  ,                    ," "

- 352564,782338,2020-07-09,0.0030,Y,YI,"Yellow iris <5m2    ",IRIS,PSE,CIPC,MOF ,100,    ,000,    ,000,200967,"1: Low (<= 1 plant/m2)   ","2: few sporadically                     ",C: Cursory      ,PC3                 ,"3 small plants"
-

**Comment by ghost** [comment]
@micheal-w-wells 

![IAPP_Migration_v2.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/c7a53e61-8d09-4e7d-8104-0d0169bbc402)

The survey data is in the Teams Files:  Full_02_Survey_v1_529179.7z

**Comment by micheal-w-wells** [comment]
Loading data took a bit longer, but it will now work for other kinds of attributes (treatments, biocontrolouputs, etc), as well as support longer running imports (no issues with keycloak sessions etc).  

@dogcomplex stepped up and is going to work on the UI stuff this afternoon/tomorrow while I'm off to keep it moving forward and restyle the Site attributes as part of that.
