### ISSUE TITLE
IAPP Migration: Mechanical Treatments

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#164]
**Describe the Task**
Migration of IAPP "Mechanical Treatments" into InvasivesBC app

**Acceptance Criteria**
- [x] Load Mechanical Data
- [x] Make UI

**Comment by ghost** [comment]
@micheal-w-wells 

Mechanical treatment csv file posted.

![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/e212b6e2-9bef-4283-8533-c86107493e1e)

**Comment by ZoeSimon** [comment]
> **Describe the Task**
> Migration of IAPP "Treatments" into InvasivesBC app
> 
> **Acceptance Criteria**
> 
> * [x]  Load Mechanical Data
> * [ ]  Load Chemical Data
> * [ ]  Load Biological Data
> * [ ]  Make UI
