### ISSUE TITLE
User shape for trip upload/draw

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#1659]
DECISION: NO MORE PLAN MY TRIP PAGE.

INSTEAD, ON THE RECORDED ACTIVITIES PAGE (ON MOBILE only for now) (do as child component that can be passed to map container):

- [x] new button on map that will open a dialogue to let user manage their shapes/trips
- [x] dialogue will ask if user wants to make a new boundary and options are (yes - draw, yes - upload KML, or choose uploaded KML, no)
- [x] user sees a list of shapes they have created, name, date, and whether it was from a KML or user drawn
- [x] pull in code from KML uploader to facilitate above KML requirement (from layer picker)
- [x] if user chooses to draw their own shape - they should get to draw a polygon, whether or not they chose poly or kml they get to name it.
- [x] checkbox to indicate if its a shape they want to cache next to each.
- [ ] look at the code in map container for "show / cycle trips " this will be handy for displaying user shapes.

**Comment by CrystalChadburn** [comment]
@hpertaia and @micheal-w-wells and @plasticviking  to meet thursday at 420pm pst.

**Comment by micheal-w-wells** [comment]
@plasticviking bug me on discord and we can chat through it - we're going to reference these shapes from the records page when we cache, and layer caching will be simplified to "cache all layers for selected trips"
