### ISSUE TITLE
Solve the circle option from the map geometry drawing options

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1690]
circles aren't real.

we do not need the circle drawer in the map tools but we need to keep the point marker which currently autofills area to 1m square.

Ignore the POI, this is for new InvasivesBC records only.  

@micheal-w-wells  to populate this.

**Comment by CrystalChadburn** [comment]
@plasticviking  Hey Rob have you made any progress on this one or are you waiting for feedback/input from Mike?

**Comment by CrystalChadburn** [comment]
@plasticviking  we need to park this one please.  Just remove the circle drawing tool from the map tools and we have handled the point in the metabase reports already.  We will pick this up later.

**Comment by micheal-w-wells** [comment]
brennan has the point markers taken into account - just disabling circle drawing as requested.
