### ISSUE TITLE
BC GEO BUG

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1701]
bc geometry is taking a while to load resulting in "geometry not found in bc" error messages sporadically.
- either make the bc layer smaller or draw a shape making sure to include all islands.
- [x] brennan made a better geometry
- [x] put a timeout on the geo compare

**Comment by micheal-w-wells** [comment]
@sam-warren  I think #1705  will fix but seeing a record linking error in dev, are you getting it?
