### ISSUE TITLE
OS4 - Make the InvasivesBC pipeline work

### ISSUE THREAD

**Issue by rstens** [bcgov/invasivesbc#176]
- [x] App build/Deploy
- [x] API build/Deploy

**Comment by rstens** [comment]
We are fully in OCP4 now. 
https://console.apps.silver.devops.gov.bc.ca/k8s/ns/7068ad-tools/pods/invasivesbci-api-build-311-9-build/logs

**Comment by ZoeSimon** [comment]
All cleared by Roland :)
