### ISSUE TITLE
Get PROD version of metabase standing up

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1761]
- assign crystal chadburn and brennan webster master administrators.

**Comment by plasticviking** [comment]
@CrystalChadburn Started looking at this today. Clarification question: Do we want to share the instance Mussels already has? (https://metabase-7068ad-prod.apps.silver.devops.gov.bc.ca/) and setup our own content within here or provision a separate instance? Additionally, do we want a vanity domain for this or is the .silver.devops.gov.bc.ca domain ok?.

**Comment by CrystalChadburn** [comment]
Hi Rob,

We need a separate instance than the mussel app please.   I think we would prefer a vanity URL but wondering how long that would take?

Thanks!
Crystal
