### ISSUE TITLE
Recorded Activity page record display and filter tasks

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1762]
- [x] remove colour wheel for the "all records" table 
~~- [ ]  default colours for activity types~~ duplicate
- [x] figure out filtering by date range or if year is only option (which is fine)
~~- [ ] test that clicking on the record shows the record on the map and vise versa~~duplicate
- [x] fix or remove toggle filters on map button (i forget what this was for).
- [x] @CrystalChadburn to create list of fields we want to see for each record in the table (and create the ability to scroll right to see more)

**Comment by micheal-w-wells** [comment]
allow for IAPP record sets on recorded activities page:
- [ ] display to user as IAPP while under the hood allow for points of interests, so we can add more types of records later
- [ ] add appropriate iapp columns (use top level fields on IAPP POI to start).

**Comment by micheal-w-wells** [comment]
recorded activities page map tasks:
- [x] display each record set as a cluster layer at higher zooms
- [x] create tests to generate records to see on the map.
- [ ] display count for each record cluster
- [ ] display as geojson at smaller zoom
- [ ] update lean endpoints to use same sql as not-lean endpoints and test that we are getting the same set of ids

**Comment by micheal-w-wells** [comment]
default colours for activity types
