### ISSUE TITLE
for mobile - change appstate to use sqlilte so browser refresh doesnt clear user filters

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#1778]
Test this first to make sure it doesn't have it's own browser cache.  

Need to make sure if users clear their cache it doesn't lose their datasets cached.

Close if not an issue.

**Comment by sam-warren** [comment]
Appstate is stored in SQLite on mobile. Confirmed in DBeaver. Will test and make changes if necessary.

**Comment by sam-warren** [comment]
Cannot produce issue in testing. Closing.
