### ISSUE TITLE
Embedded reports page continued....

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1811]
- [ ] turn on filters for all columns
- [x] create 4 categories of reports on the embedded reports page and move all the tables from metabase (Dev) onto this page.   Categories include: IAPP Queries, InvasivesBC Reports, InvasivesBC Spatial Queries, and User Uploaded KMLs (that we will eventually restrict to show only the kmls that the signed in user has uploaded.
- [x] Once Rob has it functioning, Sam will take over and make the page user friendly/pretty.
- [x] Change the name of this tab to just be "Reports" instead of "Embedded reports".

NOTE: this will be in web only so not required for mobile.

**Comment by CrystalChadburn** [comment]
@sam-warren please take this ticket on.  Moving it over to in progress now as the check boxes still need to be done including the filtering.

**Comment by plasticviking** [comment]
@CrystalChadburn @sam-warren The filtering needs to be setup within Metabase -- there's nothing to do on the app side.

**Comment by CrystalChadburn** [comment]
@plasticviking  and @micheal-w-wells to discuss how to turn filters on in metabase so they show up in the app OR whether the coding Mike is doing for the reported activties page will work.  We definitely need the filters working on the reports page because otherwise we can't extract them as there are way too many records to do a full download of all of IAPP etc.

**Comment by CrystalChadburn** [comment]
closing this as a new ticket was created for just the filtering.
