### ISSUE TITLE
API Changes to Filtering

### ISSUE THREAD

**Issue by sam-warren** [bcgov/invasivesbc#1838]
Linked to #1762 

- [x] Update ActivityTableHelpers.tsx to include columns listed in dropdown (see email)
- [x] Ensure that jurisdiction and species pos/neg filtering is working in current state of query
- [x] Update where clause on activities-lean to match that of activities query
- [x] Add partial matching functionality for grid fields above columns, on save filters button pressed, send new search filter criteria and update table with results
- [x] Update logic of where clause for arrays: "does anything in this array match the search or is anything in this array like the search substring?"
- [x] Link GridFilters in ActivityGrid.tsx to getActivities searchFilterCriteria
- [x] Make sure map updates when filters are updated

**Comment by CrystalChadburn** [comment]
@sam-warren  can you provide an update where this is at so we can decide if it's a priority for you to continue please.
