### ISSUE TITLE
Terms and Conditions page

### ISSUE THREAD

**Issue by sam-warren** [bcgov/invasivesbc#1842]
[InvasivesBC Data Share Agreement May2022.pdf](https://github.com/bcgov/invasivesbc/files/8704236/InvasivesBC.Data.Share.Agreement.May2022.pdf)
See @CrystalChadburn for T&C content

- [x] Create new public (unauthenticated) route in HomeRouter (see HomeRouter.tsx to see how these are created) called Terms & Conditions at route /home/terms-and-conditions
- [x] Create Terms and Conditions page component with the content that @CrystalChadburn provides. Using `<Box>` is a quick and easy way to throw together a text page. See LandingPage.tsx for reference, where the info box is created (Line 227-289)
- [x] Have link in LandingPage.tsx (line 251) link to new Terms and Conditions page you created. You may want to change it to a button that calls `history.push('/home/terms-and-conditions');`. See "Request Access" button for reference
- [x] change the text on the home page that links to the information attached (and emailed) to say By using this Application, you agree to the Data Sharing Agreement (and make Data Sharing Agreement the hot link).

**Comment by CrystalChadburn** [comment]
@gdalcengio  Hey Gabe, i have attached the content here in a pdf for what we want the users to see when they click on the terms and conditions.  We could just have it open up in a pdf or you can make a new page with the content on it.   Need to make sure everything that is on here is on it though including the May 2022 date for the version.  I will email you the word version too now as this ticket won't let me attach word in case you need to copy/paste.
