### ISSUE TITLE
Query and filter on reports page

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1900]
- [ ] on reports page, users need to be able to filter all columns to reduce the number of records before they extract to excel or other file type.@plasticviking and @micheal-w-wells to discuss how to turn filters on in metabase so they show up in the app OR whether the coding Mike is doing for the reported activties page will work better. Filters are required otherwise too many records to download to excel (crystal tested though and got 20000 records)

- [ ] on reports page, users need to be able to query/restrict any of the reports by a kml they have uploaded.

This is for web only.  Not required for mobile.

This replaces the remaining tasks for #1681 and #1811.

**Comment by micheal-w-wells** [comment]
#1933 covers this and will show business area how they can self maintain this via metabase setup
