### ISSUE TITLE
Public facing map fix

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1962]
- [x] allow all public users to see the on-click fields for iapp records and invasivesBC observations, but block the users from opening any records.  

- [x] if they try to open up the record by clicking on it, provide an error message that says "InvasivesBC Access is required to view complete records. Access can be requested at the top right of the page under the Person Icon" (or something like that).

- [x] fix error message as indicated in the comments below

- [x] hide the example/fake InvasivesBC donuts from the map in PROD until they are working.

- [x] invasivesBC observations are showing

- [x] IAPP records are showing
 
- [ ] required for web, optional for mobile.

**Comment by CrystalChadburn** [comment]
in prod, as of june 20th, 2022, the public facing map give this error (see attached pic).

**Comment by CrystalChadburn** [comment]
<img width="956" alt="publicfacebug" src="https://user-images.githubusercontent.com/82186073/174663436-93bf2c2d-0d71-450f-a1b7-71a1bfc9157b.PNG">

**Comment by bburciaga** [comment]
Currently checked boxes are in unmerged PRs

**Comment by bburciaga** [comment]
Reviews in Progress for changes

**Comment by CrystalChadburn** [comment]
@micheal-w-wells to review and push if ready.

**Comment by bburciaga** [comment]
Going to close issue since most are merged and one is done in another branch

**Comment by bburciaga** [comment]
Also unsure if works on mobile
