### ISSUE TITLE
Monitoring Forms

### ISSUE THREAD

**Issue by bburciaga** [bcgov/invasivesbc#2011]
**Describe the bug**

**To Reproduce**
1. Create a new Record that is associated to Monitoring
2. Fill out a form
3. Try filling out `Evidence of Treatment` field or `Treatment Pass`
4. See fields get cleared out after

**Expected behavior**
Shouldn't clear any field and let you complete a form for Monitoring records.

- [ ] fix monitoring form

**Comment by micheal-w-wells** [comment]
field clearing fixed.  have a 'redux remaining' task list for forms i'm going to flush out separately
