### ISSUE TITLE
Map being slow issues

### ISSUE THREAD

**Issue by bburciaga** [bcgov/invasivesbc#2013]
Check these in order:
- [ ] start by turning everything off, and then one at a time add features back on to find components causing grief.
- [x] check network tab to see if something is requesting more often than it needs to. (check calls to activities lean) SAM AND BRIAN TO WORK TOGETHER ON THIS.  Wait until Brian is completed his work on the map and then review with additional issues that Sam has indicated are fetching too many times.
- [ ] IAPP pop up refactor changes the extent of the map (SAM WORKING ON THIS)
- [x] disable base map when rendering topographical map  BUT DO NOT BREAK THE LITTLE BLUE DOT (find me/track me).  May not need to do this as it shouldn't be that large.

**Comment by sam-warren** [comment]
Added flags to branch bug/2013 to show where duplicate calls were being made
