### ISSUE TITLE
Monitoring Form Bug

### ISSUE THREAD

**Issue by sam-warren** [bcgov/invasivesbc#2028]
Some fields not letting users type on Monitoring Forms

linking issues

**Comment by micheal-w-wells** [comment]
need to validate if its a spatial seeding thing - test if it works on the island or not for each field

**Comment by micheal-w-wells** [comment]
mike to fix with other form state stuff

**Comment by micheal-w-wells** [comment]
all the typing stuff is fixed.  linking in redux can be another issue
