### ISSUE TITLE
Overlapping IAPP label issue 

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#2073]
ISSUE: When zooming into an area with many IAPP sites, the labels that currently have a white, semi-transparent background overlap and make it difficult to see the map underneath.

Suggested fix options (in order of preference by crystal):
- [x] create a toggle on the side of the map to turn the labels on or off.
- [ ] only have the labels show up when you get into a closer zoom level (ie. 200m or so?
- [x] remove the white background of the labels and make them a bolded black or white colour so they only have text and not the white background - might be hard to see.

**Comment by CrystalChadburn** [comment]
@micheal-w-wells please add comments/ideas/suggestions

**Comment by micheal-w-wells** [comment]
what I did for second box is just not let user draw more than 1000 labels per layer at once, this stops screen from being covered in labels if zoomed too far out.

for data issues like many sites nearly on the same point - we'll have to keep thinking about how to do that.

**Comment by CrystalChadburn** [comment]
Still need to figure out how to have the labels responsive to zoom level.
