### ISSUE TITLE
IAPP Migration: Chemical Treatments part II

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#211]
**Describe the Task**
Migration of IAPP "Chemical Treatments" into InvasivesBC app

**Acceptance Criteria**
- [x] Make UI

**Comment by ghost** [comment]
Only display the variables in the image.

The names of the variables can be more meaningful if possible. Talk with Shasko

![IAPP_Migration_v5.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/1a462c60-a2c0-47b1-a082-a927948766b5)
