### ISSUE TITLE
move history path / url / tab state to redux

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#2122]
- [x] can hit refresh and still be on current page.
- [x] handles token expiry / auth still

**Comment by CrystalChadburn** [comment]
@sam-warren please action this and talk to @plasticviking first

**Comment by sam-warren** [comment]
Remaining bugs / TODOs
- [x] Logging out returns user to last visited page, but shows blank when they don't have permission to view it
- [x] Navigating to a new path prompts keycloak login again, should not
- [x] Page not found not triggering properly on * route
- [x] Keycloak redirect still defaults to redirect to /home/landing, causing undesired redirects
- [ ] More mobile testing
