### ISSUE TITLE
add leaned out web map components & state

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#2123]
- [x] manage state in redux & sagas
- [x] where am i, zoom, accuracy, and toggle base layer work.

**Comment by micheal-w-wells** [comment]
@sam-warren breaking off layer picker req so i can work on it without redoing what you started

**Comment by micheal-w-wells** [comment]
- [ ] lean web layer picker

**Comment by CrystalChadburn** [comment]
@sam-warren please confirm with @micheal-w-wells where this is at
