### ISSUE TITLE
mobile OFFLINE activity page

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#2126]
TLDR: missing activity/offline saga actions and handlers for sqlite, need to move sqlite global from dbcontext to redux store.

- [x] can create record offline
- [x] can get single record offline
- [x] can save record offline
- [ ] can delete record offline
- [x] can cache record
- [x] can submit to web
- [ ] display local offline records in record sets when offline

**Comment by CrystalChadburn** [comment]
@micheal-w-wells here's a ticket with some offlining tasks....
