### ISSUE TITLE
Form BUGS and critical fixes

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#2154]
General bugs for all forms:
- [x] it says "deletion not authorized" and won't let me delete my own record.  (allows me to click the delete button but the record doesn't get deleted.  I can edit and re-save no problem.   
- [x] pmp field doesnt let you erase garbage without a popup that says 'proceed click'
- [x] error clearing issue
- [x] increase the area limit.  Should be 50Ha which is 500 000 sq. m.  

In aquatic chemical treatment form:
- [x] when you click "off" under tank mix, i get a white screen.  Reproduced this three times.  Can't get back to form.

not form fixes - moving to other tickets:
~~- [ ] records are not showing on the main map or the map within the current activity form page - this has been disabled on purpose to fix some map stuff, but including it here to make sure it gets put back on.~~

~~- [ ] table on crystal's account only showing her own records under "all invasiveBC records" - should show all records from all users for all roles.~~

**Comment by sam-warren** [comment]
Point 4 is intentionally disabled per map improvements.

**Comment by sam-warren** [comment]
Point 1 could be caused by the sanitizedSearchCriteria being passed to delete activity endpoint. Could be the case that trying to delete one record checks all other records as well. Will investigate further.

**Comment by sam-warren** [comment]
Point 2 requires more information - as a master administrator I can view other users'  records in dev, however it could be the case that the logic that determines what records other users can see has broken somehow, or perhaps there are no records created under users with roles that Crystal's roles permit her to view.
