### ISSUE TITLE
Monitoring Form fixes - important but not bugs

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#2155]
Aquatic and Terrestrial Chem monitoring forms:
- [x] remove the "efficacy comments" field currently under chemical treatment info and mech terr aqu mont info headings on both forms.
- [x] Edit the title of the "Activity Monitoring Chemical Terrestrial Aquatic Plant" and "Activity Monitoring Mechanical Terrestrial Aquatic Plant" forms to have an 'or' in between Terrestrial OR Aquatic.
- [x] Edit the heading within the Activity Monitoring Mechanical Terrestrial Aquatic Plant form that currently says "Mechanical Terrestrial Aquatic Monitoring Information to just be "Mechanical Monitoring Information"
- [x] remove "legacy IAPP release ID" on chemical and mechanical treatment monitoring forms. (Leave it on the biocontrol release monitoring form).

**Comment by brennanwebster** [comment]
@CrystalChadburn everything is working from this ticket except the "or" isn't showing on the mechanical monitoring title

**Comment by CrystalChadburn** [comment]
@micheal-w-wells and @sam-warren the second bullet is not complete.  The title name isn't changed on the mechanical monitoring form

**Comment by micheal-w-wells** [comment]
my mistake, i see i just made it work for one form and not the other, i'll fix it so it works for both
