### ISSUE TITLE
IAPP Migration: Biological Treatment part I

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#218]
**Describe the Task**
Migration of IAPP "Biological Treatments" into InvasivesBC app

**Acceptance Criteria**
- [ ] Load Biological Data
- [x] @mikeshasko needs to provide csv file

**Comment by micheal-w-wells** [comment]
need a csv in order to start

**Comment by ghost** [comment]
CSV with header add to Development/files

https://bcgov.sharepoint.com/teams/02125/Shared%20Documents/Development/FULL_06_BiolTreatments_v1_12454.csv

**Comment by ghost** [comment]
![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/bfc34a42-d96f-4556-8281-9cfb8d31256d)
