### ISSUE TITLE
IAPP Migration: Chemical Treatment part I

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#219]
**Describe the Task**
Migration of IAPP "Chemical Treatments" into InvasivesBC app

**Acceptance Criteria**
- [x] Load Chemical Data
- [x] @mikeshasko needs to provide csv file

**Comment by ghost** [comment]
Data uploaded:  FULL_05_ChemTreatments_v1_186464.7z


![IAPP_Migration_v5.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/5b92a8a3-8d5f-434e-8ba2-2bd2e4713055)
