### ISSUE TITLE
Form bugs sept 23 2022

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#2196]
- [x] In the chemical treatment forms (both mechanical and chemical), the product application rate and delivery rate fields won't allow decimals to be entered any more.  Please enable decimals but keep with no negative numbers.

- [x] In the chemical treatment forms (both mechanical and chemical) the service license field is no longer autofilling with 00000 for Crystal as a government user, and it won't let me override by entering a number.

**Comment by micheal-w-wells** [comment]
these drop down fields never let you override with a value not in the list.  still trying to figure out why you don't get the 00000 value autofilled though

**Comment by micheal-w-wells** [comment]
for me - based on my employer i get two options to choose from
