### ISSUE TITLE
Metabase Reporting: Update plant observation views

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#220]
**Describe the Task**
Have a look at previous migration to create views for observations and update where required so they're visible in Metabase.

**Additional Context**
- Previous migrations don't exist anymore

**Comment by micheal-w-wells** [comment]
Got one done for terrestrial plant, the main 'observation' one that spans all types.  @mikeshasko when you're back we can run through and do a QA in metabase once it's stood up and make the final tweaks.

Should probably do small 1-2 est tickets for the other views (other animal obs, various treatments, monitorings, etc) vs dump them all in one as the QA of all of them alone is bigger than a 2.

**Comment by micheal-w-wells** [comment]
plant treatment views - migrations + QA
