### ISSUE TITLE
Geometry/Area size limit

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#222]
**Describe the Task**
There should be an error message provided to the user when they're creating a geometry.

- Terr Plant obs / treat 1 to 10000 sq m
- Aquatic plant obs/treat 1 to 100,000 sq m
- All animal activity 1 to 100,000

**Comment by sdevalapurkar** [comment]
setup for such custom validation is taken care of in #241 
future area restrictions, etc can be added in matter of few lines in `customValidation.ts` file
