### ISSUE TITLE
IAPP Migration: Efficacy Monitoring Mechanical Treatment part I

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#223]
**Describe the Task**
Migration of IAPP "Efficacy Monitoring of Mechanical Treatments" into InvasivesBC app

**Acceptance Criteria**
- [x] Load Efficacy Monitoring of Mechanical treatment Data
- [x] @mikeshasko needs to provide csv file

**Comment by ghost** [comment]
@dogcomplex  @micheal-w-wells @ZoeSimon 

The mechanical monitoring csv and mockup are loaded into "files"

Provide the corresponding mech monitoring line under the Mech treatment where there exists a corresponding monitoring record of the same mechanical treatment ID.

Not all treatments will have monitoring records and in some cases there may be more than 1 monitoring record against a given treatment.

![IAPP_Migration_v4.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/da1ff753-98f6-406d-898f-6f209f11ac2a)

**Comment by ZoeSimon** [comment]
This is @micheal-w-wells depiction of me when I look through all these tickets in progress @dogcomplex 
![image](https://user-images.githubusercontent.com/62561887/102287381-30194380-3eef-11eb-906a-332937e1b3b6.png)
