### ISSUE TITLE
IAPP Migration: Efficacy Monitoring for Mechnical Treatment part II

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#224]
**Describe the Task**
Migration of IAPP "Efficacy Monitoring of Mechanical Treatments" into InvasivesBC app

**Acceptance Criteria**
- [x] Make UI

**Comment by ghost** [comment]
@dogcomplex  @micheal-w-wells @ZoeSimon 

The mechanical monitoring csv and mockup are loaded into "files"

Provide the corresponding mech monitoring line under the Mech treatment where there exists a corresponding monitoring record of the same mechanical treatment ID.

Not all treatments will have monitoring records and in some cases there may be more than 1 monitoring record against a given treatment.

![IAPP_Migration_v4.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/cd6ba6c3-958e-4f8a-a982-7394849b9c02)
