### ISSUE TITLE
Positive and negative record flow on my records page

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#2301]
TABLES
- [ ] create two new columns called "Most Recent Positive" and "Most Recent Negative" under the InvasivesBC record sets (main set and any subsequent record sets they create) to allow users filter down for just the most recent record on a location.  It is understood that if any part of the record is the most recent (ie there are partially overlapping records), the full record will show even if only a part of it is most recent.

- [ ] Rename the existing columns in the invasivesBC record tables that will continue to show all the positive and negative records to be "All Positive" and "All Negative".

Use the views created by Brennan (current positive and current negative) to populate the new columns.

**Comment by micheal-w-wells** [comment]
`+/- observation status


names of the views 
  - current positive observations 
    - should be per species, meaning each record can be in there more than once
  - current negative species
    - should also be PER species - same record can be there more than once


UX 

 A) 

  - works for when you know what you're looking for, not really exploring

    - advanced filter -  "current positive" or "current negative"
        first select dropdown - '+' or '-'
        second will be species


 B) 

  - columns for display, maybe filtering:

    - do allow for filerting here:
      - has current positive (boolean)(record in current positive view at all)? true: false  

    - skip filtering here for now:
      - list of current species for that record (concat all species for that record in current positive view )



    - do allow for filerting here:
      - has current negative (boolean) (record in current negative view at all)? true: false
        
    - skip filtering here for now:
      - list of current negative species for that record (concat all species for that record in current negative view)


 C) ? 
`


rolling with option B for now
