### ISSUE TITLE
Ensure IAPP and InvasivesBC records are showing on the public facing map again

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#2304]
Bring back the iapp and invasivesBC records on the public facing map before you log in.

Bring back the iapp and invasivesBC records on the public facing map before you log in.

Techy todos:
-[ ] 

How activities page/activity page + map works

1. user logs in / stays logged out
2. auth request complete
3. app fetches geojson for both activities and points of interest / iapp stuff --- works up to here logged out
4. map init action
      grabs all the filters for each record set from local storage
      puts filters into state (usersettings.recordsets)
      loop over each recordset, and fetch the IDS ONLY for that recordset
        activities endpoint (id only flag)
        points of interest endpoint (site_id only flag)

recordsetlayersrenderers - just filter the 2 big feauturecollections by recordset IDLists - no new server fetches

5. user clicks on recordset - iapp tablerows get || activity tablerows get - these will get full rows for display
     these actions call the same endpoint, 
    but without the id only flag, and use the same filters, but pass paging variables, ans sorting keys

what needs to change for public:

- [ ] check role / logged in before calling admin shape endpoint
- [ ] hide the boundary thing for now - nice to have when other stuff done - put it back, but dont upload or pull from server 
- [ ] activities and points of interest endpoints:
      need to work while logged out BUT:
        - [ ] can't return person name && can't filter by any name
        - [ ] dont worry about hiding columns - just dont pull them from server
- [ ] activiy page - can disable the activity page saga while logged out  
- [ ] other misc ui stuff:
    - [ ] hide the new record button
    - [ ] double check tabs make sense for public

**Comment by micheal-w-wells** [comment]
This issue is more of an 'epic' - The team shifted to working on getting the new layer format to work before doing this to avoid extra rework.  Doing smaller increments/tickets to get there, will keep this ticket around for info but not drag through sprint point tracking as its too broad.
