### ISSUE TITLE
IAPP Migration: Efficacy Monitoring of Biological Treatment part I

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#232]
**Describe the Task**
Migration of IAPP "Efficacy Monitoring of Biological Treatments" into InvasivesBC app

**Acceptance Criteria**
- [ ] Load Efficacy Monitoring of Biological treatment Data
- [ ] @mikeshasko needs to provide csv file

**Comment by micheal-w-wells** [comment]
need a csv in order to start

**Comment by ghost** [comment]
CSV in Development/files

https://bcgov.sharepoint.com/teams/02125/Shared%20Documents/Development/Full_08_BiolMonitoring_v1_8138.csv

**Comment by ghost** [comment]
File loaded to Teams/development/files : Full_08_BiolMonitoring_v1_8138.csv

![IAPP_Migration_v6.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/ff46d604-d8e2-4105-bbf1-ea517f814ce9)
