### ISSUE TITLE
Business BCEID not working with forms - can't save/submit

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#2322]
As of Nov 18, the bceid user can no longer submit any forms.   Crystal watched this happen via shared screen.

See below for screenshot of console errors that occurred AFTER he pressed "save form".

The user is able to open the new form, create a geometry (although there were bugs with not being able to remove a pin when accidently chose "drop pin" and then wanted to draw a polygon", they fill out all the form including all the mandatory fields, and the employer and funding agency autofill based on the access as expected.  Everything seems to be working fine until the user clicks "save form" then it removes what the user had entered in all text fields, and is showing all the mandatory fields in red even though they have a value chosen and still showing in the field.  It just doesn't recognize it as a value.  Therefore, no matter what the user attempts to do, they cannot save a form and therefore cannot submit a form.

Contact shaun.chadburn@northcowichan.ca for testing after fix is complete.  

This user was able to submit records in Sept and edit them earlier in nov with no problem. 

![image](https://user-images.githubusercontent.com/82186073/204397589-a9d1e571-aacf-461d-ab0a-1ac4f99d0790.png)

**Comment by micheal-w-wells** [comment]
has been narrowed down to a typo in access, rob was able to use a bceid successfully, as was I.

@brennanwebster we can review the problem users access together
