### ISSUE TITLE
IAPP Migration: Efficacy Monitoring of Biological Treatment part II

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#233]
**Describe the Task**
Migration of IAPP "Efficacy Monitoring of Biological Treatments" into InvasivesBC app

**Acceptance Criteria**
- [ ] Make UI

**Comment by micheal-w-wells** [comment]
need a csv in order to start

**Comment by ghost** [comment]
![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/ba488d5f-c968-42bc-a9bb-6382b7d90f05)
