### ISSUE TITLE
Recordset issues

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#2368]
- [x] Have to click filter icon to make rows populate
- [x] "My Drafts" and "All InvasivesBC Activities" default to being on but check boxes are not checked
- [ ] Have to drag map to make IAPP sites render after enabling labels or enabling recordset
- [x] Clicking filter button makes page jump
~~- [ ] Typing in the column filters doesn't filter as you type, have to click save and apply filters~~ (this is by design, to avoid expensive calls to server (particularly when combined with search feature))

**Comment by micheal-w-wells** [comment]
- [ ] Have to drag map to make IAPP sites render after enabling labels or enabling recordset
