### ISSUE TITLE
What here issues

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#2403]
- [x] Whats here rows not showing all activities in box
- [x] Sometimes first page shows no rows but subsequent rows have data
- [x] Window sometimes renders half off the page
- [x] Button shows on current activities page
- [x] Clicking an activity on whats here popup will make the whats here box you drew become that activities geometry
- [ ]

**Comment by micheal-w-wells** [comment]
some state management code setup for last point but not quite done (whats here whos editing)

**Comment by micheal-w-wells** [comment]
going to just hide it on activity page for now.  can open separate issue for 'enable whats here on activity page' if/when we need to prioritize that
