### ISSUE TITLE
Front end for public facing map

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#2429]
- [ ] if they try to open up the record by clicking on it, provide an error message that says "InvasivesBC Access is required to view complete records. Access can be requested at the top right of the page under the Person Icon" (or something like that).
- [ ] no personal information showing or treatment info - only show observations and iapp surveys.

**Comment by micheal-w-wells** [comment]
doing more granular tickets for this one vs drag it around, can keep for info

**Comment by micheal-w-wells** [comment]
I think we're all good for this as there's no on click for the record in that view
