### ISSUE TITLE
Protecting biocontrol development release sites V1

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#2453]
Version 1 - allow certain users to only see the protected biocontrol release and biocontrol release monitoring records.
~~Version 2 - have a skewed location or blob (tbd with SMEs) so all users can see general region of activity but not exact location.~~ Captured in

**Comment by micheal-w-wells** [comment]
@CrystalChadburn for now I hid them for anyone but admin, but you can start uploading them and we can flush out how to display them
