### ISSUE TITLE
Redesign the main activites page to put the all the plants stuff together followed by all the animal activities

### ISSUE THREAD

**Issue by sdevalapurkar** [bcgov/invasivesbc#261]
Redesign the main activities page to put the all the plants stuff together followed by all the animal activities

[ ] Create a top line check box of drop down that highlights 3 groupings of activities:

[ ] Plants
[ ] Animals
[ ] Special

Within Plants and animals are the observation / treatment and monitoring activities.
The "Special" activity forms will house the wildfire and transect type activities

**Comment by ghost** [comment]
![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/172fd9a9-7f75-4340-b62f-da6c7259513a)

**Comment by ZoeSimon** [comment]
**Efficacy Monitoring**
