### ISSUE TITLE
Batch issue ticket from crystal's email 

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#2618]

**Comment by micheal-w-wells** [comment]
- big outstanding items;
  - user testing batch list
 -[brij ] Is there a way to delete batches that you uploaded, but then saw a bunch of errors and no longer want to proceed with it?  need to build a delete button?
 
 -[brij] Is there a way to scroll to the right when reviewing your batch to see all the records….. when reviewing the errors (ie. what is in red), can only see the first 12… users will need to scroll along to review for errors before executing.

 -[x] Aquatic and terrestrial observation batch ….  The voucher – date verified and voucher date collected fields are showing as mandatory but they shouldn’t be.
 -[x] Aquatic and terrestrial observation batch – did not find an error with the record that I had no geometry for, and did not go into drafts or submitted table.  It just ignored this line completely. 
 -[x] I chose to put errors into drafts, but they didn’t go there…. They all went into submitted, even with errors, except the one with no geometry as per #4.

 -[bren] The area isn’t calculating via the geometry, submitted records all have 0 as area both in the table, extracts and when looking at each form individually.

 -[x] I put crystal Chadburn as person 1 for all records, and Brennan webster as person 2 for a couple of them, but after executing, it put Brennan into the person field for all of the reco
rds, sometimes twice (as confirmed by pulling the records out in an extract using my project code – see attached for what I put in compared to what I pulled out).
 -[x] The activity date overrode what I submitted into the current date and time when I submitted the batch.  That field should stay with the date the user enters via batch as there is a separate fields for the record created field that also took today’s date and time.
- [x]? Also, it let me put in the date YYYY-MM-DD as well as some with the date plus time without showing any errors.
 -[x] The invasive plant fields are not populating into the table (eg. 23PT060E4 and 23PTO240B) and current positive and current negative fields are therefore not working either.  All positive and all negative are blank.  But the species I submitted via batch do show up in the csv extracts and when opening the individual
