### ISSUE TITLE
negative occurrences in batch observation forms

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#2729]
- [x] if a user choses N (negative) in the Negative/Positive Observation column, then the 3 conditionally required fields should not be required (density, distribution, and life stage).   Currently they are required in batch so it needs to be changes for both terrestrial and aquatic observation (launched with just terrestrial so need that at a minimum).

**Comment by CrystalChadburn** [comment]
@plasticviking  can you please try to fix this urgent item tonight and let us know if you are successful.  It was an oversight and now people can't batch their negative observations with their positive ones as it stands.

**Comment by plasticviking** [comment]
@CrystalChadburn I've addressed this in a hotfix to prod. Please test when able.
