### ISSUE TITLE
Configuring Geoserver for Openshift

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#273]
**Describe the Task**
Installing Geoserver in Openshift. @popkinj input for additional info needed.

**Acceptance Criteria**
- [x] Docker image V1
- [x] Change admin password - Dockerfile
- [x] Add PostGIS data store - Dockerfile
- [x] Add test RISO layer - Dockerfile

MW:  Hi!  I didn't get to finish this but left notes on where it's at for someone to pick up.  Coles notes:  I think you can use the image build thats deployed in ocp4 dev, but you're going to need to make a volume and load the geoserver zip of data that's on their readme I mention below.

**Comment by micheal-w-wells** [comment]
Easy dockerhub image import is out the window as it runs as root.  We'll be the first team to get it running at all on openshift 4.  Trying to get one of the lab teams who did it in OCP3 to share a config but no dice yet.

I _think_ that just moving the read/writes out of root in https://hub.docker.com/r/geonode/geoserver/dockerfile might get us somewhere but I'm not sure.

**Comment by micheal-w-wells** [comment]
Continuing to dump notes here in case anyone picks this up while I'm on holiday:

I forked the above dockerfile's repo which you can find here: https://github.com/micheal-w-wells/geoserver-docker .  There's a 'not_root' branch where I have:

* Changed the location of a few config files to not be in root dir
* Added a script to take the current running user to /etc/passwd to avoid OCP complaining about it not being in there.  You can read more about how the platform generates a user and issues with that and running as root here:  https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html

**Comment by micheal-w-wells** [comment]
Here's my hacky way to get a custom docker container into openshift with the least amount of openshift:
$ docker build .
...
Successfully built 470833936638
$ docker tag 470833936638 michealwwells/geoserver_mike
$ docker push michealwwells/geoserver_mike

You would then go to the GUI to import a new image, specify michealwwells/geoserver_mike and bam it deploys.

**Comment by micheal-w-wells** [comment]
Geoserver image now I think is good (no more root or permissions issues), but the dc needs a volume and mountpath with the zip of geoserver data as referenced on the readme here https://github.com/micheal-w-wells/geoserver-docker .

I took a stab at getting a linux pod mounted to a volume so I could upload the zip but got stuck.

**Comment by popkinj** [comment]
Thanks @micheal-w-wells. I've done persistent drive stuff before for PostGres... So I'll have a look.
