### ISSUE TITLE
Multiple species entry > Create multiple observations on same point

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#276]
**Is your feature request related to a problem? Please describe.**
Feature.

**Describe the solution you'd like**
There are times where multiple species are found on the exact same point.  While the recently developed copy form function could be used here, the workflow to recreate the exact same point would be very clunky.  Where the copy function is more likely to be used is with similar observations in a nearby area.  

Ideally they could select multiple species on the form, and the app will create one observation record (with a specified geometry). 

**Describe alternatives you've considered**

**Additional context**
Subsequent ticket from #157

**Comment by ghost** [comment]
This type of workflow will be required for the aquatic observation. 
Workflow:
Capture a location on a lake and assign it a nominal area/geometry (specifically a circle).
Record a set of common variables/ attributes that will get assigned to all subsequent species selects.
The user adds 1 or more specifies records (much like the chem treatment form)
In the back end individual observations are created. The copy function autofills the common values.

**Comment by sdevalapurkar** [comment]
Using the clone activity functionality, currently the user will be able to specify a geometry and all the form fields they wish to (including a species) and then press clone. The original activity will be stored as it was but will also be cloned identically with the same geometry and form fields. Now, all they have to do is select a different species and continue cloning and repeating this process for as many species as there are

Is this an acceptable workflow? @mikeshasko

**Comment by ghost** [comment]
Yes for the aquatic plant and aquatic animal workflow...

1 location of the water is selected
A set of "water" related variables are collected.
1 or more species (with some species variables) are then collected.

So in the end each x,y point could be its own "observation" or we could have the one observation with multiple species.
