### ISSUE TITLE
GPS Track workflow for Geometry

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#278]
**Is your feature request related to a problem? Please describe.**
Feature

**Describe the solution you'd like**
Put a button on activities to start recording a track as a geometry.  Once clicked the button should change to 'stop' in order to end the track.  Nice to have would be resume.  There should be an input for interval to GPS ping.

While recording is 'on', use the Ionic Geolocation service to get the devices gps position.  Build a list of coordinates.  As each point is added to the list, update the activities geometry with an updated linestring.  This will automatically rerender the map with the users track, without having to write custom leaflet interactions.

**Describe alternatives you've considered**

**Additional context**

@mikeshasko update however you like.  I put a roughed out implementation plan for whatever dev tackles this if you prioritize the ticket, but change the workflow to whatever you want.

**Comment by micheal-w-wells** [comment]
#595

**Comment by ZoeSimon** [comment]
- add button for people to be able to capture and copy their UTMs to use for transect forms

**Comment by micheal-w-wells** [comment]
Should be a new issue no?  Different ask?

**Comment by ghost** [comment]
The capture or a track (as per #278) is a different ask than the capture of the current location into the form.

Shasko will itemize the transect ask into a new ticket. It is, however, somewhat related as we need to collect the native IOS position from the device and add to the form via a button.
