### ISSUE TITLE
Observation and Treatment linking V1

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#281]
The creation of an observation is to be an independent activity. 

The creation of a treatment, however, typically would be carried out on (or around) an observation as it would only occur if the target species had been previously identified.

Scenario # 1

First click on an existing observation.
Define a treatment geometry that encompasses the area treated. It may include all or part of the underlying observation.
Include a provision to capture an underlying observation ID in the treatment record.

Scenario # 2

Create a new treatment with a new geometry

**Comment by micheal-w-wells** [comment]
I'd like to do something like this under the hood for whoever takes this one:
```
activity {
//...usual activity properties
related_activities : [
      { activity_id: 123, relationship_type: peer }, // this is the only one we need for this ticket
      { activity_id: 523, relationship_type: parent },  // in the future for treatment planning/projects and other things
      { activity_id: 234, relationship_type: child } // other half to parent-child.

]
}
```
