### ISSUE TITLE
Herbicide variables

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#282]
**Describe the Task**
As per discussions with Denise at Sprint Review on Dec 16th

- [x] Capture the area of the treatment extent ( ie as per a regular activity)
 
For each herbicide "Add" capture these variables:
- [x] Herbicide

 - Application rate (litres/ ha)
 - Amount of herbicide (litres)
 - Mix delivery rate (litres / ha)
 - [x] Tank volume (litres)

 - [x] Area of the specific treatment area (ha)  - autofill based on calc
 - [x] Dilution (Percent of product mix)  - autofill based on calc

**Comment by ghost** [comment]
![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/c610fd03-b6b1-487d-8689-84c20aae2769)
