### ISSUE TITLE
V2 template user testing #3

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#2941]
- [x] reverse hide filter button
~~- [ ] clicking enable recordset button should re render map~~
- [x] making a new record should take you straight to the form
- [x] activity load issue
- [x] drawn geometry should clear when switching from a new form to records page
~~- [ ] can't sort recordset columns~~
- [x] Self intersection validation not working

**Comment by micheal-w-wells** [comment]
recordset sorting

**Comment by micheal-w-wells** [comment]
map rerendering quirk on first load
