### ISSUE TITLE
v2 template user testing feedback #4

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#2979]
_mw: leaflet overriding my css here, will come back to it but workaround is minimize form_
~~- [ ] Records not showing on map~~
_mw: mismatch in ids in geojson between envs, need cronjob to regen per env nightly, will make another ticket
~~- [ ] Not contained in operator doesn't work for spatial filters~~
_mw: known.  enhancement should be another ticket_
- [x] Removing spatial boundaries also removes filters
_mw: assuming this means its removing extra filters beyond the spatial one mentioned, will look in to it_
- [x] Button ribbon gets in the way of drawing boundaries
- [x] After uploading kml the list of available kml filters doesnt update, but the layer picker list does update
- [x] Generate csv button doesnt work with spatial filter
- [x] Two shapes appear when drawing polygon, have to click twice to erase both

**Comment by micheal-w-wells** [comment]
- [ ] Layer picker resets to defaults on refresh

**Comment by micheal-w-wells** [comment]
- [ ] Ribbon buttons hide behind recordset popout sometimes

**Comment by micheal-w-wells** [comment]
- [ ] Layer picker disappears when scrolling near the bottom (when you have records popout open, seems like the button ribbon is the culprit)
