### ISSUE TITLE
Storing map state in database

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#31]
**Storing map state**
- [x] Capture save event
- [x] Capture edit event
- [x] Capture delete event
- [x] Store new and edited geometries
- [x] Remove delete geometries
- [x] resurrect saved geometries on map load

EDIT:  breaking this big ticket down so we don't keep carrying it around.

**Comment by micheal-w-wells** [comment]
- [ ] Store map zoom level
- [ ] Store map extent
- [ ] Resurrect map state on map load
- [ ] figure out why leaflet.draw isn't redrawing circles
- [ ] draw point marker
