### ISSUE TITLE
Need a fix so that when any SUBMITTED record gets opened, it doesn't show red errors 

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#3135]
This seems to appear when the batch loader has slightly different validation rules than the form.  For example, 23PTMB7549508 was submitted in a batch (ID 730) but when opened in invasivesBC shows that the access description is an error which is confusing because the text says it needs to be fixed before being submitted from a draft but it has already been submitted.  

Options include removing that red text anytime a record is submitted, or better yet, fixing the batch uploader to match the validation rules of the form itself (so far only have the access description needs to be 5 or more characters long discrepancy found).

**Comment by micheal-w-wells** [comment]
Definitely the best plan is to make validation the same everywhere, and fix the data when we spot issues.  We can fix these specific examples in this ticket (or add more if you find them), but in any case hiding the errors in some cases would just lead to data issues and validation confusion down the road, best to let the app tell us what its trying to tell us.
