### ISSUE TITLE
Simple Bulk Actions

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#316]
**Describe the task**
Given a multi-selected record, this is the action to delete, undelete and change access role. 
 
**Acceptance Criteria**
- [x] Delete and Un-Delete actions
  - This logic should assume it receives an array of activity IDs, and then does the right thing with them from there.
  - Records are never actually deleted, they are just marked as deleted (via the `deleted_timestamp` column).
  - This will likely need new endpoint(s) for deleting and undeleting an array of records.  Under the hood, the endpoint will look pretty similar to the PUT activity endpoint, but just updating the deleted timestamp, and not other fields in the record.
- [ ] Change role action
  - Nick: Thinking about this more, I think this bullet needs to be flushed out a bit more, and likely brought into its own ticket, as there are a few different options for this, which will likely impact all of the current endpoints (as they would nee to honour the role security at a record level, which they don't currently).  A good option is to add Read and Write array columns to the records, and then we can control what roles get set in each, and the API can use that to determine what records it allows someone to read/write.

**Additional Context**
Look at Material UI tables when actioning this ticket

**Comment by dogcomplex** [comment]
Bulk deletions are up, with a UI for deleting and endpoints for deleting and undeleting.  I think Change Role Action will need to be another ticket, and associated with the user accounts list whenever it's ready

**Comment by ZoeSimon** [comment]
@dogcomplex will ticket #121 suffice for this Warren? @mikeshasko I'm assuming needs to flush it out a bit more.

**Comment by dogcomplex** [comment]
@ZoeSimon hey sorry!  Yeah, I think the multi-select ability should be moved into that ticket (which itself can probably be broken up to several mini tickets).  Making the endpoints might be a good start there, but yeah - best done as a separate ticket
