### ISSUE TITLE
Testflight release

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#319]
**Describe the task**
Invasives app testflight release. Manual workflow needs to be completed for testflight release. 

- [x] produce build in xcode
- [x] get access to app store connect if you dont have it (from MW)
- [x] get bundle id (from MW)
- [x] get app signed in gov signing portal
- [x] upload to testflight
- [ ] grant access to build to testers

**Comment by micheal-w-wells** [comment]
Scripts and instructions are in the repo + readme.  Waiting on platform services for access for the other devs so we can work together to resolve the profile provisioning issue.

**Comment by ZoeSimon** [comment]
@mikeshasko to work with Crystal and send a list to @micheal-w-wells
