### ISSUE TITLE
Metabase Reporting: Plant Treatment views

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#327]
**Describe the Task**

Treatment views
- [x] chemical treatment
- [x] bio treatment
- [x] mechanical treatment

**Additional Context**
related to ticket #220 & #328

_Originally posted by @micheal-w-wells in https://github.com/bcgov/invasivesbc/issues/326#issuecomment-754991683_

**Comment by micheal-w-wells** [comment]
lets call the rest of these 3's:

Plant Monitoring
Animal Observation
Animal Treatment
Animal Monitoring
