### ISSUE TITLE
Metabase Reporting: Plant Monitoring views

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#328]
monitoring views
- [x] Main Monitoring View
- [x] Biological Terrestrial Plant Monitoring with codes
- [ ] Biological Terrestrial Plant Monitoring Summary (codes, descriptions, base activity and monitoring fields --new format for all)
- [ ] Chemical Terrestrial Plant Monitoring with codes
- [ ] Chem Terrestrial Plant Monitoring Summary
_Originally posted by @micheal-w-wells in https://github.com/bcgov/invasivesbc/issues/326#issuecomment-754991843_

**Comment by micheal-w-wells** [comment]
@mikeshasko are the ones i listed above the same as efficacy monitoring (and warrant a re-name) or is that something else?

**Comment by ghost** [comment]
Yes - the plant mech/chem/biol monitorings (efficacy) all use the same percentages in 10% increments.

**Comment by micheal-w-wells** [comment]
I think plant views are good for now.  I'm giving them another QA round with Mike once he gives me the final spatial overlay columns, otherwise nothing to action on.
