### ISSUE TITLE
Pipeline deploy to Prod and Test

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#336]
**Describe the Task**
Use example in Lucy-web

**Comment by NickPhura** [comment]
Worked correctly in Test.  The prod environment is the exactly same (the only manual intervention needed is to create the secrets, which I have done), so there should be no issues running it there.

Any failures in either environment are almost certainly resource related, though the recent replica changes I made to reduce the number of pods in test and prod should fix that.
