### ISSUE TITLE
Research ways to manage access in Metabase

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#337]
There's a lot of utility for our stakeholders as far as metabase goes, but until we come up with an access model and implementation we can really only give @mikeshasko, Val, and Crystal access.  This ticket is to come up with the model/method, and there'll be another for the implementation.

From reading the docs it seems pretty doable:
"you can assign users to groups and you can give groups access to data. Groups can have restrictions on databases, tables and raw SQL access. Metabase will figure out which dashboards, questions and pulses a given user can see based on their groups data access permissions. In short we focus your attention on what data the user has access to as opposed to which dashboards they can view. "

https://www.metabase.com/blog/Permissions/

**Comment by micheal-w-wells** [comment]
@mikeshasko

If you can come up with the list of groups, and what data you think they should see that would be a good starting point.

**Comment by sam-warren** [comment]
There is a way to integrate Keycloak SSO with metabase. This would be an effective means of getting a user's permissions based on their roles, similar to how we do in the app. A user would log in using their IDIR to their Metabase dashboard and, depending on what Keycloak roles they have, would only see data they have permission to see. Keycloak SSO integration can be found here: https://www.metabase.com/docs/latest/enterprise-guide/authenticating-with-jwt.html
