### ISSUE TITLE
User sees no options in employer, funding agency, and role when filling out access request

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#3385]
![image](https://github.com/user-attachments/assets/05e4da59-b22a-41d3-92c5-2ba11b4824de)

**Comment by LocalNewsTV** [comment]
Is this for an existing or new user?
I don't have access on Prod and tested with Chrome/Firefox/Edge on my personal windows computer. All of them generated the lists appropriately.
