### ISSUE TITLE
Mobile testing 2024-08-15

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#3426]
- [x] geometry autofill fields will sometimes not fill after drawing geometry (happens with point too)
- [x] geo tracker makes a line but can't create polygon
- [x] geo tracker needs to track smaller intervals, < 1m maybe?
- [x] Cant cancel out of point area prompt, prompt just repeatedly pops
- [x] Layout size will sometimes change making the header very big, seems to be no way to revert, and this hides all the map buttons
- [x] #3476
- [x] #3440
- [x] shapes created with geo tracker do not fill area field (related to the line issue further up)
- [x] #3441

**Comment by LocalNewsTV** [comment]
@brennanwebster 

- [ ] geo tracker makes a line but can't create polygon
    - When drawing a Polygon, the shape is closed AFTER you toggle the GPS Draw tool off, signalling you want to stop. This reduces errors being thrown when shapes are intersecting / overlapping. Until the shape is closed, it is treated as a Linestring
        - This is different from the Polygon tool on the map, which always kept the Polygon closed while you drew it. 
    - Can add an alert explaining this detail, if wanted
- [x] geo tracker needs to track smaller intervals, < 1m maybe?
    - Having it too low causes unnecessary points to be placed due to GPS Sway, which will make more invalid shapes, and make it harder for users to correct errors.
    - Already, if I just stay in place, the sway from the GPS will hop around creating shapes and plotting points
   
![image](https://github.com/user-attachments/assets/a13aaaf3-2c5c-464e-b999-5f0a8582c74d)
[source](https://www.gps.gov/systems/gps/performance/accuracy/)

- [x] Cant cancel out of point area prompt, prompt just repeatedly pops
    - This has always been the case, as well as for custom drawing LineStrings
    - Refactoring this will be carried out in #3405,
- [x] shapes created with geo tracker do not fill area field (related to the line issue further up)
    -  This should be filled in once you **close the shape with no errors**. But will investigate to make sure nothing strange happening
