### ISSUE TITLE
:zap: Research Playwright for Frontend

### ISSUE THREAD

**Issue by LocalNewsTV** [bcgov/invasivesbc#3439]
# Describe the task
> If the task will only make sense to a dev, add a :zap: to the title.

Research integrating Playwright testing into the existing application. 

## Value Add
Finding a testing suite that suits the needs of our application allows stronger test writing, helping prevent breaking changes between app/package updates, improving reliability.

## Findings
- Write findings here after research period

**Comment by plasticviking** [comment]
Will pass this one back to you shortly. I've been working on adding stubbed auth functionality to both frontend and backend to facilitate testing.
