### ISSUE TITLE
Mobile app testing 2024-08-29

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#3456]
- [x] choose offline user doesn't bring back new record button
- [x] geotracker constantly following the user makes it difficult to move the map, sometimes freezes the map altogether (i think it would be fine to turn this off) #3440 
- [ ] creating new record sometimes causes crash (chem treatment mostly)
- [ ] turning off geometry tracking causes crash sometimes
- [x] #3460
- [x] #3461
- [x] sync button stuck loading, run sync button greyed out so cannot sync

**Comment by LocalNewsTV** [comment]
@plasticviking  I can look into these ones if you aren't already
 - *choose offline user doesn't bring back new record button*
 - #3440
 - *turning off geometry tracking causes crash sometimes* I can see if I can replicate in a simulator, but would be helpful if @brennanwebster  had any info about iOS Version or model of device

**Comment by plasticviking** [comment]
I think the fix for the sync stuck thing is a timeout on the submit to abort the run if it's not progressing. Is there any more information on the reproduction for this one? Seems like it can only happen in really marginal network conditions.

**Comment by plasticviking** [comment]
@LocalNewsTV I grabbed/fixed the missing new record button already. Didn't catch your comment in time. That one was small. I haven't dug into the duplicated draw controls yet.

**Comment by brennanwebster** [comment]
> @plasticviking I can look into these ones if you aren't already
> 
>     * _choose offline user doesn't bring back new record button_
> 
>     * [find me button jumps the whole map when it moves #3440](https://github.com/bcgov/invasivesbc/issues/3440)
> 
>     * _turning off geometry tracking causes crash sometimes_ I can see if I can replicate in a simulator, but would be helpful if @brennanwebster  had any info about iOS Version or model of device

the model was A2757, not 100% sure on the iOS version but I updated all of the iPads about a month ago
