### ISSUE TITLE
Mobile: Sync error on completed activities

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#3533]
Form was completely filled out without errors and saved to draft. After hitting run sync the status is Error, unclear why.

From #3506 
Saved a local activity to draft without errors, went online and clicked sync, status changed to "Error". The activity didn't make it into the database at all, not sure what happened

**Comment by plasticviking** [comment]
Added some checks, added an error detail pane to give more context on a failure, and blocked submitting when you don't have a valid token. I think I've handled most cases where this could occur.
