### ISSUE TITLE
Public map activites only viewable on topographic map

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#3567]
For the four basemap buttons on the public map, clicking the first three hides the activities. The fourth one shows the activities but forces you to use the topographic basemap. Should be able to view the activities on the satellite basemap also.

**Comment by LocalNewsTV** [comment]
@plasticviking  Might be part of your current work

**Comment by plasticviking** [comment]
Yes, this will be fixed shortly.
