### ISSUE TITLE
Mobile: geometry tracker saying shape is outside bc when it isn't

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#3575]
I haven't been able to reproduce this but a couple users had an error about the geometry being outside of BC when it wasn't.

**Comment by LocalNewsTV** [comment]
Likely culprit is the BC Area fails to load and would return false, triggering a "Not within BC" claim. Changed the error handling so a different message is displayed if this is the case, prompting the user to try again.
