### ISSUE TITLE
Mobile: geo autofill fields not autofilling after drawing geometry

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#3578]
While offline and drawing geometry with the tracker or the regular draw tools, when geometry is finished the geo autofill fields are still blank. I wasn't able to reproduce this but users reported it.

**Comment by LocalNewsTV** [comment]
@brennanwebster 
For the users reporting this problem, was this a 'Sometimes' issue, or did it happen reliably for them?
Like you, I cannot replicate it, so knowing frequency might help with figuring out if its device specific.

**Comment by LocalNewsTV** [comment]
![Image](https://github.com/user-attachments/assets/4577c248-9a14-4924-b7b7-5d66b9fa1e69)

If the shape fails to autofill, try having the user tap the shape to put it back into the editing mode, and then click on the map to refire the functions that do the autofilling.

This will help in identifying if something is sometimes failing, or there's a deeper seated issue to dig into.
Thank you !
