### ISSUE TITLE
Mobile: labels on IBC/IAPP recordsets do not work

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#3584]
While online with either recordset turned on and labels turned on the labels do not appear. 

Another weird behaviour is the polygons in the InvasivesBC recordset will only appear if the labels are off. If you turn labels on you will only ever see points, if you turn them off the polygons will appear.

**Comment by plasticviking** [comment]
Done (in dev). Needs test to confirm @brennanwebster
