### ISSUE TITLE
Make public map new react-components version

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#3690]
- [x] Public map is react component version
- [x] Topo, Sat (HD & SD) all work
- [x] Zoom controls work
- [x] Public pmtile layers work

**Comment by meghna0593** [comment]
This is completed for web and mobile. 
The PR is not merged into dev yet, needs some more testing of offline features. In this PR we have two map components, one for authenticated(old) and one for unauthenticated(new) user. Need to test for possible leaks and/or app crashes.
