### ISSUE TITLE
Change max zoom level on pmtiles for public map to 24

### ISSUE THREAD

**Issue by meghna0593** [bcgov/invasivesbc#3709]

**Comment by meghna0593** [comment]
On running 'export-map' job to update the zoom level led to this [bug](https://github.com/bcgov/invasivesbc/issues/3708)

**Comment by plasticviking** [comment]
I think we ought to discuss this one. That introduces a lot of size and duplication for very little benefit.

**Comment by meghna0593** [comment]
tldr; We decided this change was not needed
