### ISSUE TITLE
Mobile: "New Recordset - Activity" text should be wiped automatically when naming custom recordset

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#3733]
If you add a new ibc/iapp layer of records and click the edit icon to edit the name, you have to manually delete the text. It should just remove it automatically so the user can type the name they want.

**Comment by LocalNewsTV** [comment]
consideration for implementation:

Have default Recordset name be empty instead of this string.
when Recordset name is empty, display this string instead.
