### ISSUE TITLE
Zoom to selected activity on map

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#376]
On Cached/All Records page:
Let user select one or more records from the list and then hit a button (see comment below) that zooms to an extent that contains all of them.

**Comment by micheal-w-wells** [comment]
![image](https://user-images.githubusercontent.com/955467/120229712-8874a100-c202-11eb-8796-b3805c991abb.png)

**Comment by micheal-w-wells** [comment]
related to the work i'm doing, i think it should be done by christmas
