### ISSUE TITLE
Aquatic Plant Observation won't sync (in dev)

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#397]
**Describe the bug**
Record fails on sync.

**To Reproduce**
1. Fill aquatic form
2. Check for errors (none)
3. Mark as reviewed
4. Sync

**Expected behavior**
Should turn green.

**Screenshots**
![image](https://user-images.githubusercontent.com/955467/104534929-09235f80-55ca-11eb-95cd-3732be075969.png)

Here's the request:
{"activity_id":"157f5bdd-a643-4d0c-94a3-678f36fff21b","created_timestamp":"2021-01-12T18:33:25.705Z","activity_type":"Observation","activity_subtype":"Activity_Observation_PlantAquatic","geometry":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[-125.642669,54.826008]}}],"media":[],"form_data":{"activity_data":{"general_comment":"asdf","access_description":"asdf","paper_file_id":[{"description":"asdf"}],"activity_date_time":"2021-01-12T10:33:25-08:00","reported_area":0,"latitude":54.826008,"longitude":-125.642669},"activity_type_data":{"observation_type_code":"OP","negative_obs_ind":true,"observer_first_name":"asdf","observer_last_name":"asd","sample_number":"1"},"activity_subtype_data":{"invasive_plant_code":"BW","specific_use_code":"PF","proposed_treatment_code":"CM","flowering":true,"plant_life_stage_code":"MMF","plant_health_code":"BD","plant_seed_stage_code":"NO","range_unit_number":"234","legacy_site_ind":false,"early_detection_rapid_resp_ind":true,"research_detection_ind":false,"special_care_ind":true,"biological_ind":false,"voucher_submitted_ind":false,"water_depth":3,"sample_point_number":"asdf","secchi_depth":51,"voucher_submission_detail":"1"}}}

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sdevalapurkar** [comment]
handled by https://github.com/bcgov/invasivesbc/pull/403

monitorings will need extra work
