### ISSUE TITLE
Question about code tables for @mikeshasko  and @rstens

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#401]
Question about code tables for @mikeshasko  and @rstens:  Title and description (and i think one more column) of the code table header are all the same.  Are there plans to do anything about that?  This can be a ticket to track work if so if not answer here for @klefler  and we can close.

_Originally posted by @micheal-w-wells in https://github.com/bcgov/invasivesbc/issues/394#issuecomment-760477443_

**Comment by rstens** [comment]
Ah, that is content. The description can be anything the title is used by the query.

**Comment by klefler** [comment]
@rstens - could I suggest adding business descriptions in the code_header_description column. For example; for the soil_texture_code type, adding a description such as "_The soil texture code provides details regarding the quality and water retention of soil in a site where an invasive plant has been identified._"
