### ISSUE TITLE
"primary_user_name_1" or "observer_1" ? 

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#402]
Do we want to roll with "primary_user_name_1" or "observer_1" ? The Form spec and API and DB are mismatched.

@mikeshasko  @klefler

_Originally posted by @micheal-w-wells in https://github.com/bcgov/invasivesbc/issues/394#issuecomment-760479179_

**Comment by ghost** [comment]
The name of the variable needs to reflect a primary and/or a secondary observer, first and last name.

primary_observer_first_name
primary_observer_last_name
secondary_observer_first_name
secondary_observer_last_name

or

observer1_first_name
observer1_last_name
observer2_first_name
observer2_last_name

The later is preferred as biohub may have more than the 2 observers that InvasivesBC only requires
