### ISSUE TITLE
Create Layer - National Parks

### ISSUE THREAD

**Issue by popkinj** [bcgov/invasivesbc#437]
## Overlay requirements
- [x] Isolate WMS service in BCGW getCapabilities service
- [x] Add layer to Geoserver Configuration as a proxy
- [x] Activate TMS service in Geoserver
- [ ] Adding overlay to map
- [ ] Configure and test offline capabilities

**Comment by webgismd** [comment]
just reading this.. @popkinj  is this to cascade the WMS layers from DataBC through another Geoserver implementation as part of this project? is there documentation on this approach ? Just curious mostly, and if I can assist.

**Comment by popkinj** [comment]
You got it @webgismd . 
Our tool requires TMS layers. So we were going to proxy the WMS layers from DataBC. Would love any assistance if you have the time ☺.

**Comment by webgismd** [comment]
will you be enabling geowebcache for these layers? we can touch base let me know what time works!
