### ISSUE TITLE
Observation for Multiple Observations

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#442]
The user shall have the ability to select one or more observations from reference activities and create a observation record for those children observations. The use case for this is because there are many cases where the invasive species has spread and now the area that the specialist is planning on treating will be expanded to include the union of not just the selected observations, but also an additional area. So we just want to provide the ability to create one parent observation that encapsulates the entire union of the observed area.
 
When the user selects one or more observation records, they will be taken to a screen to create their observation record. They will be able to view the children observation records on the map. Once they create the parent observation record and enter the form fields, they will be prompted to create a treatment record. The observation geo will be shown on the map and the basic info section of the form will be populated with the parent observation entered information.
 
Here they can now create their treatment with the entire observed area specified.

**Comment by ZoeSimon** [comment]
Email from Crystal on January 20th:

After our conversation yesterday at 1pm, I realized one change needed to what we agreed to regarding the new idea that when you click on “enter a chemical Plant treatment” it would redirect you to the observation page and force an observation prior to each treatment.  Current policy is only a survey before the first treatment in the year, and sometimes there will be multiple follow up treatments that do not need an observation.  In other words, there should only be one observation only per year, and it should occur before the first treatment.  Additional observations should NOT occur before subsequent treatments.  

Therefore we request that each time a user clicks on “enter a treatment” (for chemical, mechanical and biological), a prompt comes up that says “is this the first treatment of the year on this infestation?” and if you click “yes”, then it redirects you to the observation page, and if you click “no”, then it just allows you to enter the treatment without forcing the observation first.

Additional observations could still be added if new species found while doing a second or third pass treatment, but in that case the user can just go back in after their treatment and add a new observation record.  Also, if a treatment person stumbles over a "new" area adjacent to the first pass observation/treatment during second pass, they would have to enter a new observation and separate treatment of it.

Val and I have discussed and agree on this approach.

**Comment by ghost** [comment]
After our conversation yesterday at 1pm, I realized one change needed to what we agreed to regarding the new idea that when you click on “enter a chemical Plant treatment” it would redirect you to the observation page and force an observation prior to each treatment.  Current policy is only a survey before the first treatment in the year, and sometimes there will be multiple follow up treatments that do not need an observation.  In other words, there should only be one observation only per year, and it should occur before the first treatment.  Additional observations should NOT occur before subsequent treatments.  

Extracts … most recent survey

The Invasives application is very spatial orientated. Not capturing a geometry observation upon a second/followup treatment negates:

•	the opportuntity to compare Obs1 (A + B with new)+treat1  to obs2+treat2 over time.
•	recording changes in the observation over the time gap between treatments
•	rationale as to why the treatment2 geometry might have changed over the treat1 geometry



Therefore we request that each time a user clicks on “enter a treatment” (for chemical, mechanical and biological), a prompt comes up that says “is this the first treatment of the year on this infestation?” and if you click “yes”, then it redirects you to the observation page, and if you click “no”, then it just allows you to enter the treatment without forcing the observation first.

 Provide an input field on the treatment form that sets the treatment iteration:

•	[ ] Is this the first treatment of the year on the targeted invasive species?
•	If YES … directed to obs page … must create observation … then proceed to treatment (#1)
•	If No … 
o	Does the initial observation accurately represent the current size (larger) and shape (extent)
o	If YES… proceed to create a new observation… then proceed to treatment (#2)
o	If NO … then proceed to treatment (#2)

Explictly field to capture

[ ]  1st treatment of year

[ ]  2nd treatment of year

[ ]  3nd treatment of year
