### ISSUE TITLE
Well ID & Well Proximity

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#450]
**Is your feature request related to a problem? Please describe.**
- [x] "Well ID" and "Well proximity" missing on plant terrestrial observation and all plant treatment forms as part of the Basic information

**Requirement**

The provincial wells layer (BCGW) provides a spatial/data content for approximately 60,000 well locations representing about 70% of the known and documented wells in the province.
As part of any/all plant activities, the location of wells (known and those newly observed) need to be identified and integrated in all treatment plans and activities as the use of herbicides are restricted within range of a well (distance varies).
As most wells are on private land, treating on crown land still needs to account for nearby wells.

**Describe the solution you'd like**

- [x] Only the Well ID and the position need to be retained from the wells database
- [x] Well locations should be symbolized as a point feature on the leaflet map
- [x] Move over or click should display the Well ID and UTM

If feasible on the mobile...
- [x] Once the geometry of the activity is set, the closest well (from the cached set) needs to be identified
- [x] The well ID and distance (metres) needs to file the WellID and WellProximity fields as part of the basic information for the Observation and the Treatment activity.

If it is not feasible on the mobile to relate the anchor point of the activity to the well points, then the WellID and WellProximity fields would be <null> or <tba> on the form. Once the sync record is process on the backend, these fields would be determined.
- [x] The WellID and WellProximity fields should therefore always be visible and populated on all cached activities.
- [x] The WellID and WellProximity fields would not be editable at any point (just like area) 

**Describe alternatives you've considered**

_Open to alternative methods._ 

**Additional context**
- Users have to determine where the wells are before drawing geometry (chem treatment record)
- Error to user to say that they can't treat in a location because there's a well nearby

_Screen shot in comments below._

**Comment by ghost** [comment]
Well locations appear as a default layer.
Mouseover/click displays the ID and location.
![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/6e0355ce-392c-42b0-94db-10315066c70a)

**Comment by ZoeSimon** [comment]
@popkinj Here's one that is important to tackle

**Comment by micheal-w-wells** [comment]
@popkinj sounds like we are gonna be caching some layer data to query with this one.  Was your plan for this to just cache well data for the province or to fetch it for a region?

**Comment by popkinj** [comment]
Was planning to cache the closest well (within 500m) and the associated
attributes. The API end point for this is already done.

**Comment by ZoeSimon** [comment]
@popkinj Jamie to show @micheal-w-wells what needs to be done to close this ticket.

**Comment by micheal-w-wells** [comment]
use turf to get distance to well
