### ISSUE TITLE
Page to request user to send email to grant access

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#453]
**Is your feature request related to a problem? Please describe.**
Page to request user to send email to Mike Shasko gov email to grant access.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NickPhura** [comment]
@ZoeSimon The only thing outstanding is the generic email to set on the 'request access' page.  Not an immediate issue while its all still under development of course. I added a ticket to the backlog #478

**Comment by ZoeSimon** [comment]
> @ZoeSimon The only thing outstanding is the generic email to set on the 'request access' page. Not an immediate issue while its all still under development of course. I added a ticket to the backlog #478

Awesome thanks for the heads up @NickPhura, I'm just working on getting some coding for the inbox creation, then we can move forward.
