### ISSUE TITLE
Sorting and filtering additional UI

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#459]
There will need to be some updates to the search page, to refine the filters and the columns that we display, etc.  But a basic set of fields/filters are there, and all of the big pieces of code to support the functionality (front/back) are in place.

[SEARCH PAGE MOCK UP.docx](https://github.com/bcgov/invasivesbc/files/7722264/SEARCH.PAGE.MOCK.UP.docx)

Review #1252 as well to ensure they work together.

- [x] remove the current search page once the new myrecords table sort/filter/search tables are built.

**Comment by CrystalChadburn** [comment]
@micheal-w-wells  i uploaded a search page mock up here showing my vision of the fields we will need.  Please read the note at the top of the word doc re the public search page versus the user log in search page.  Also if you have other ideas or think this is duplicating metabase at all, let's chat.

**Comment by micheal-w-wells** [comment]
We've come so far on this broadly titled ticket - would be nice to close it and call it 'v1'.

**Comment by CrystalChadburn** [comment]
@micheal-w-wells once i see your page in dev, i will close this one and make a v2 for what is left.
