### ISSUE TITLE
Offline solution for keycloak & user roles

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#471]
v1: 
- [ ]  let user choose to login, or view public layout
- [x] let user choose online status (done) 
- [x] if online & the user chose to login, they should get redirected to a login page and then subsequently their roles should be available in web and cached on mobile.
- [x] if offline status - the user should have a cached role that determines layout, but not get booted to a login page.

**Comment by micheal-w-wells** [comment]
this one will be easier to do after i fix a caching bug - just worry about #896 and #646 for now

**Comment by micheal-w-wells** [comment]
thanks @sam-warren this will work for v1
