### ISSUE TITLE
Uploading & Caching User's layer file

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#474]
**Describe the Task**
Users want the ability to upload and cache their own layer file + metadata to guide their field operations when offline. @popkinj outlined that this would be possible if it's in a KML/KMZ format, not a shapefile format. 

- [ ] Ability for user to upload KML/KMZ file in the picking layer tab of "Plan my Trip" tab
- [ ] Metadata from their file is viewable to user in standardized format
- [ ] Sample KML/KMZ file that users have worked with are attached in email to @popkinj (may contain sensitive info so not attached here)

- [ ] UI to allow for this feature dealt with in ticket #475

**Comment by popkinj** [comment]
Hey @ZoeSimon 
By "Meta Data", are we referring the attribute data of each spatial feature?

**Comment by ZoeSimon** [comment]
> Hey @ZoeSimon
> By "Meta Data", are we referring the attribute data of each spatial feature?

I think so, like that table of data when you select a spatial feature within said file that you can display in google earth:
![image](https://user-images.githubusercontent.com/62561887/109227276-e8c3f480-7774-11eb-95bf-3447b04b6b2c.png)

These are the spatial features within that file?:
![image](https://user-images.githubusercontent.com/62561887/109227435-304a8080-7775-11eb-8fcb-30e451c0c45a.png)

**Comment by popkinj** [comment]
Perfect. Thanks Zoe.
