### ISSUE TITLE
UI for "Pick a Layer"

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#485]
**Describe**
These are asks coming from the business area after preliminary review:

- [ ] Need ability to display multiple layers at once 
- [ ] Needs to be able to re-order layers, pick X # of layers and then select order they appear (accordion like imapBC, or something that is intuitive to users) 
- [ ] Needs to be able to see metadata associated with the layer (likely more important for main Map page)
- [ ] Error or instruction for uploading too many layers or being too zoomed out.

**Comment by CrystalChadburn** [comment]
Duplicate ticket.  addressed in 589
