### ISSUE TITLE
Help text content - Animals

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#496]
**Describe the Task**
As any web / mobile user I wish to see additional information appear upon clicking a (?) icon next to any particular input field.

**Acceptance criteria:**
- [ ] use the text strings provided in this file:

**_Animal form fields will be finalized on Feb 3rd, spreadsheet with help text will be provided once business has completed it_**
- [ ] animal aquatic observation
- [ ] animal terrestrial observation
- [ ] animal terrestrial mechanical treatment
- [ ] animal terrestrial chemical treatment
- [ ] animal terrestrial biological treatment
- [ ] animal aquatic mechanical treatment
- [ ] animal aquatic chemical treatment
- [ ] animal aquatic biological treatment
- [ ] animal terrestrial/aquatic chemical efficacy monitoring
- [ ] animal terrestrial/aquatic mechanical efficacy monitoring
- [ ] animal terrestrial/aquatic biological efficacy monitoring

**Comment by CrystalChadburn** [comment]
@mikeshasko  please send me the spreadsheet for this ticket
