### ISSUE TITLE
- more map state work

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#50]
- [x] Store map zoom level
- [x] Store map extent
- [x] Resurrect map state on map load
- [x] figure out why leaflet.draw isn't redrawing circles
- [x] draw point marker
- [x] store updated circle feature radius

_Originally posted by @micheal-w-wells in https://github.com/bcgov/invasivesbc/issues/31#issuecomment-703898238_

**Comment by micheal-w-wells** [comment]
Hung up on it not drawing the circle, i can get it to remember the location, drag it around, but not draw the circle (always get the broken image icon).

**Comment by popkinj** [comment]
Hmmm... May get to this one today @micheal-w-wells . Two eyes are better then one.

**Comment by popkinj** [comment]
Got points and circles to save and restore properly. @micheal-w-wells you were almost there.
Going to do a pull request and create another branch for the map extent stuff.
