### ISSUE TITLE
OpenShift Pipeline for Geoserver

### ISSUE THREAD

**Issue by popkinj** [bcgov/invasivesbc#507]
The Geoserver Openshift container is running and configured in Dev. However the Build is also in Dev and should be ported to Tools.
- [ ] Move Build from Dev to Tools
- [ ] Connected webhook to new Build in Tools
- [ ] Scale up Geoserver/increase resources

**Comment by micheal-w-wells** [comment]
At this time I think the team is able to move forward without a geoserver instance, but worse comes to worse we know how to stand it up.
