### ISSUE TITLE
form broken

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#52]
forms don't render, stuck on loading wheel

**Comment by micheal-w-wells** [comment]
seems like API doesn't like if db pod gets bounced, something to look at later but for now this is resolved via a redeployment of the api

**Comment by micheal-w-wells** [comment]
![image](https://user-images.githubusercontent.com/955467/95142713-2c1bb900-0729-11eb-9260-f5e1bd60cc8b.png)

**Comment by NickPhura** [comment]
Pushed some code that may help with this issue (assuming its the database connection pool maxing out like I suspect).
