### ISSUE TITLE
Convert to Tables: Cached Activities & Local Activities

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#525]
**Is your feature request related to a problem? Please describe.**
Feature Request/Enhancement.

**Describe the solution you'd like**
Converting the list of records on cached acitivities and local activities to display a table similar to how IAPP data is displayed in the app. Including pagination, sorting etc. 

**Describe alternatives you've considered**

**Additional context**

**Comment by CrystalChadburn** [comment]
@dogcomplex is this ticket a duplicate of what you're working on now?
