### ISSUE TITLE
Plan my Trip: All work to manage trips

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#529]
**Is your feature request related to a problem? Please describe.**
Feature request. All the work to manage a trip. 

**Describe the solution you'd like**
- [x] Stamp all record with trip or search criteria I.D.
- [x] Ability to selectively delete trips

**Describe alternatives you've considered**

**Additional context**
- [x] Zoom level 15 for caching layers
- [x] Class level to map?

**Comment by micheal-w-wells** [comment]
So far:

- [x] Rewrote page to separate 'trip' components from the plan page to pave way for multi trip.
- [x] Added 'Trip steps' that guide and track user actions on page.
- [x] Resized map as it will soon display more information.
- [x] Force one step at a time: smart accordion closing
- [x] Allow user to name trip (wip)

**Comment by micheal-w-wells** [comment]
Todo:  

- [ ] Multi trip table - incorporate Warren's work.  Choose Trip summary information to show in header
- [ ] Trip Spatial work: Geo display - need to work with or combine Jamie's cache geo.
- [ ] Trip data refresh and delete gotchas - 'smart' data refresh and not deleting data that overlaps with a trip
- [ ] Where do I go after "Plan my Trip" page? This needs to be more clear to the user
- [ ] Date range for Wells should just be "All Wells" with no date, or should just be removed from this section. Or should be better indicated what this part is for in terms of Wells and POIS
- [ ] Forms and Photos toggle for IAPP sites? These shouldn't be options for users.
