### ISSUE TITLE
Aquatic Plant Observation

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#531]
**Describe the task**
The aquatic plant observation will only have 1 species for selection. Same workflow for creating a treatment as terrestrial plant observation.

**Comment by sdevalapurkar** [comment]
@ZoeSimon this ticket is invalid - instead we actually want to make the terrestrial one allowed to have multiple species

**Comment by sdevalapurkar** [comment]
pls lmk if we can close it
