### ISSUE TITLE
Layer optimization - Zoom levels

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#534]
Work on once all layers are loaded.

**Comment by popkinj** [comment]
The intent is to limit the amount of map layer tiles being stored when the device is offline. Many of the BCGW WMS layers have a zoom level range that they do/don't display at. In other words, a layer that has finer detail doesn't display when zoomed out.

Goeserver sends an empty image when there is nothing to show. We can configure this to not send anything. That way, we aren't storing an empty image. This has to be configured separately for each layer.

This work is best done when all the individual layers are configured on the map.

**Comment by ZoeSimon** [comment]
@popkinj Can you provide an update on this one? (i.e. are you completing parts of this with what you're currently working on?)

**Comment by popkinj** [comment]
I believe the logic for this is done.
