### ISSUE TITLE
Layer Optimization - layer grouping

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#535]
Work on once all layers are loaded.

**Comment by popkinj** [comment]
The intent is to limit the amount of map layer tiles being stored when the device is offline. Geoserver has the ability to group layers together. This would result in one tile being sent in the place of multiple.

For example:
Parks, WHAs, & OGMAs are all protected areas that never overlap. It may make sense to group these into a new layer call "Protected Areas".

This work is best done when all the individual layers are configured on the map.

**Comment by popkinj** [comment]
Here is a test configuration of grouping WHAs with OGMAs. Seems about as speedy as all the other layers.
![Screenshot from 2021-03-04 15-24-01](https://user-images.githubusercontent.com/479074/110044496-16bdb180-7cfe-11eb-9c50-d6b539a8d907.png)

**Comment by micheal-w-wells** [comment]
Closing as we're now going to use WFS layers and prefer to have more granular toggles.
