### ISSUE TITLE
🍏 Validation rules, Required Fields & Typos

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#553]
**Describe the Task**
User testing found several validation rules/required fields. (H) = High Importance, (M) = Moderate Importance, (L) = Low Importance.

- [x] (H) Should be able to enter a second observer [ Adopt the same multi-person from Chem treatment to basic Obs activity) ]
 
- [x] (H) Should be a maximum temp for herbicide treatment   [ set flag if over 22 degrees ]  **Fix: hard error at 30 ...  tool tip 10 to 22**
 
- [x] Humidity should not be a required field  [ correct ]

- [x] (H) Soil texture should not be a required field    [ correct ]
 
- [x] (H)Secondary applicator should not be a required field [ correct ]
 
- [x] (H)When you select a negative observation as a "yes", you still have to select the density, distribution and lifestage. (i.e these fields should not be mandatory for negative observations) [ set to Not applicable ]
- [x] (L) Negative observation box needs to be added for each species now that we enables multiple species [ questionable behavior ]
- [x] (M) Should not be able to put a negative percent in for Jurisdiction [ correct, and autofill to 100 with the first selection ]
- [x] (H) REMOVE "Biocontrol field":  [ correct ]
![image](https://user-images.githubusercontent.com/62561887/109701538-fd730480-7b47-11eb-8d09-01b2a174d369.png)

 
 
**Fixes applied Friday Mar 19th 1pm  SD & MS**

**Comment by ZoeSimon** [comment]
@mikeshasko To identify which forms these bullet points are specific to.

**Comment by ghost** [comment]
Ticket updated with context / confirmations
