### ISSUE TITLE
Integrated Jurisdiction Layer

### ISSUE THREAD

**Issue by ghost** [bcgov/invasivesbc#558]
A new data layer comprised of 16 of the dominant jurisdiction spatial layers has been compiled of use in InvasivesBC to support:
 
(a) general display on the map 
(b) the autofill of additional jurisdiction variables associated with any activity (backend upon sync). Broken into Ticket #585
(c) retain as an internal layer with our database. This compilation will be updated on an annual basis.
 
Posted: https://bcgov.sharepoint.com/teams/02125/Shared%20Documents/Development/integrated_jurisdiction_Feb28.7z
 
Within the shapefile, several attributes are provided:
 
- NAME - The actual name of the land parcel, (ie park name RFI name) are included for many on the layers but not all
- TYPE - some layers include further sub-class components (ie RFI type)
- JURISDICITION - Key designation to be assigned to the activity
- DRAWORDER - number that reflects the preferred drawing order on the map to minimize overlapping

Notes:
- The attached spreadsheet details the content of the shape file.
- Several new jurisdictions are introduced. Shasko will provide an update to the code table to reflect these.
- By default, is a given point DOES NOT intersect any of the jurisdiction features, the jurisdiction is to be set to MOF
- 218,000 features are in this file
 
![Integrated_Jurisdiction_Feb28.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/f87a51eb-42f9-4d29-9835-02fbe5eab411)
 
[https://app.zenhub.com/files/296689811/434ee9f7-f627-4684-a44d-65aaadeaa008/download](https://app.zenhub.com/files/296689811/434ee9f7-f627-4684-a44d-65aaadeaa008/download)

**Comment by popkinj** [comment]
I've got the data loaded into the database and configured in Geoserver. At first glance it appears to be fairly snappy in the map. I'll do a PR to get this into Dev.
