### ISSUE TITLE
Observation and Treatment etc short I.D. - addition of new field

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#559]
**Is your feature request related to a problem? Please describe.**
The observation/treatment I.D. is too long/un-readable for users. 
e.g.: ![image.png](https://images.zenhubusercontent.com/5e78e949a7e29c75200dbef5/e5156783-5545-4796-aa4f-01f890ed2826)

**Desired I.D.** : Record Type, Unique number & letters (manageable size, unique to IAPP), date
- [x] Review with Crystal Chadburn

**Describe the solution you'd like**
Add another field to display Observations or Treatment I.D.'s so it's another field that will be shown instead to the user - this will be a more manageable I.D. for users. 

**Additional context**
This was a request and feedback from Feb 25th user testing.

**Formatting**
- [x] define as a 7 digit alphanumeric ie 21-P__-3K59___
- [x] The first 2 digits record the last 2 digits of the year ie 21
- [x] the 3rd value is a letter that will represent the general classification of the activity type ie "P" = any terrestrial plant activity (see below)
- [ ] digits 4 5 6 7 are draw from an incremental number/letter sequence 0..9 a...z  ie K4RY ranging from 0000 to zzzz
maybe:
- [ ] Exclude if feasible the letters "i" "j" "l'" and "o" as they are ambiguous with the numbers "o" and "1"

** Letter blocks**
- [ ] P - Plant Terrestrial (observation, treatment, monitoring)
- [ ] T - Transect
- [ ] M - mobile report
- [ ] D - Dispersal
- [ ] C - Aquatic Plant
- [ ] A - Animal Terrestrial
- [ ] N - Aquatic Animal
- [ ] B - Biocontrol Collection
- [ ] R - Biocontrol Release
- [ ] X - tba
- [ ] Y - tba
- [ ] Z - tba

For each letter block (with 4 digits and a set of 32 characters) 1,048,576 unique combinations exist

**Comment by micheal-w-wells** [comment]
Let's not try and pull the big id out of the app and back end as that is a big task.  Let's give them a new field and display that.

**Comment by micheal-w-wells** [comment]
All doable - although I would suggest swapping these requirements:

"digits 4 5 6 7 are draw from an incremental number/letter sequence 0..9 a...z ie K4RY ranging from 0000 to zzzz"
"Exclude if feasible the letters "i" "j" "l'" and "o" as they are ambiguous with the numbers "o" and "1" "

For:

"Use the first 4 alphanumeric characters from the system activity ID"

Without getting in to techy details - this cuts work for this ticket in half at least, and provides some consistency between the under the hood activity id's and the ids the users see (which can help in troubleshooting issues in the future).

**Comment by ghost** [comment]
The first 4 characters of the  system GUID (ie b260dc16-33f0-44d6-8b33-165eb235ee01) we use on our activities  may not always be unique over the course of a year where we expect 30,000+ entries.

"b260" is the concatenation of 2 hexadecimal values, ie b2 and 60 which would give rise to 256x256 (65,000 values).

The probability of any of the 30000 yearly records duplicating from a set of 65000 would be small. If we could check for the possible duplication on a value against the existing set of values already assigned, then the adopting the 4 characters from the GUID would be a good solution.

**Comment by micheal-w-wells** [comment]
I can do some testing and see yep.

**Comment by dogcomplex** [comment]
Went with the digits 4-7 as the first 4 digits from the old full-form UUID activity IDs, since checking for duplicates is fairly easy - just query like:

```
SELECT SUBSTRING(activity_id::varchar, 1, 4) short_id, COUNT(*) count FROM activity_incoming_data WHERE deleted_timestamp IS NULL GROUP BY short_id HAVING COUNT(*) > 1;
```
but grouping by year as well down the line.  Could be run against the DB at any time here to see how bad duplicates are.  (though currently if run it hits an unrelated softdelete issue)  As long as these short ids are used for colloquial shorthand referrals to activities, should be just fine in practice.
