### ISSUE TITLE
Pre-test issues list: Bugs

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#564]
- [ ] Plan My Trip page controls sometimes unresponsive after Wipe Local Data pressed.  Need to switch tabs and wait
- [ ] (seems to appear on multiple pages, semi-randomly)  Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in ActivityListItem (at ReferenceActivitiesList.tsx:128)

**Comment by micheal-w-wells** [comment]
checkbox 1 getting addressed in current work, the second hasn't come up but will make an issue for that if its still a thing.
