### ISSUE TITLE
Layer Styling

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#565]
**Describe the Task**
Finish styling all layers once loaded by Jamie. Brennan will support this task. 
- [x] labels for layers (they all need names on map)
- [x] styling of layers (colors, shading etc.)
- [x] Esri Imagery and BC gov
- [ ] jamie to enable/load so we can see
- [ ] Has been reviewed by @mikeshasko

**Comment by micheal-w-wells** [comment]
@popkinj what do we have to do for this?

**Comment by popkinj** [comment]
Think this is done @micheal-w-wells .
