### ISSUE TITLE
Layer Legend

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#569]
[ ] create a button on the map page that will show up on the recorded activities page as well as the current activities page called "Map Legend" that users can click to open the attached pdf.  
[InvasivesBC Map Legend_2023.pdf](https://github.com/bcgov/invasivesbc/files/11094383/InvasivesBC.Map.Legend_2023.pdf)

**Comment by micheal-w-wells** [comment]
@CrystalChadburn I think the new map maker page covers this??

**Comment by CrystalChadburn** [comment]
@micheal-w-wells  no this is the pdf of the two letter codes for the species.  I just have to make it.  then we can have a button to upload it on the app itself or just on our website for now.
