### ISSUE TITLE
Plan my Trip: INFO Ticket

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#57]
**Information pertaining to Plan my Trip page**
- [ ] #56
- [ ] #59 
- [ ] #60 
- [ ] #61

**Comment by ZoeSimon** [comment]
- [ ] get Zoe donuts

**Comment by ZoeSimon** [comment]
Spatial API to query for chunks of layers
- [ ] make back end to query for a polygon (or maybe square?) of a layer specified by a user

**Comment by ZoeSimon** [comment]
UI Component for choosing data to cache
- [ ] Build UI for what elements a user should be able to choose when it comes to caching data for their trip
- [ ] The choices the user makes are associated to the 'plan your trip' record

**Comment by ZoeSimon** [comment]
Fetching other peoples activities
- [ ] If a user has indicated they want to cache activities created by other people, they will be cached locally
- [ ] User can also pull photos (optionally)

**Comment by micheal-w-wells** [comment]
all this stuff is done
