### ISSUE TITLE
Timeboxed work for Shreyas Week Mar 22-26

### ISSUE THREAD

**Issue by ghost** [bcgov/invasivesbc#599]
REMAINING TASKS MOVED INTO SEPARATE TICKETS - May 3, 2021

**This is a running list of front end form and code tale edits for SD and MS to address during or 4 hr per session**

_**Re-visit Becky's Aquatic Plant Observation form changes from spreadsheet, she noticed that some of these still weren't captured, was it because changes weren't merged?** @CrystalChadburn  will do this week of April 19.

- [x] Re-run seed on the business code file
  - [x] Confirm 29 aquatic plant
  - [x] Confirm 206 terr plant
- [ ] Wind at 0 = no direction 
- [x] Sort agency alpha
- [ ] specific use code - none as default
- [ ] Remove tank volume
- [ ] corrections to aquatic chem treatment
- [ ] corrections to aquatic mech treatment
- [ ] create generic aquatic plant biol treatment
- [ ] Review terr plant chem monitor
- [ ] Review terr plant mech monitor
- [ ] Review terr plant Biol monitor
- [ ] Review aquatic plant chem monitor
- [ ] Review aquatic plant mech monitor
- [ ] Review aquatic plant Biol monitor

**Items changed in Codes:**
- [x] Update business code table (Mar03 version)
- [ ] set "invasive_plant_aquatic_code" for use in aquatic species drop down
- [x] Pmp updated
- [ ] Milestone typo
- [x] Move 7 aquatic semi/intertidal and to terr plants
- [x] Spartina corrections
- [ ] removed aquatic plants to new code table
- [x] Added Private agency
- [x] Spilt Rail jurisdiction
- [x] Added Federal agency
- [x] 10 granular merge to herb list
- [x] Added 00000 BC Government Ministries to pesticide Employer

**Transect changes (started from #610):**
- [ ]  When "Percent Cover" is selected under "Cover Method (fmr Count Type), the "Species within plot (fmr Vegetation Transect Points)" can’t add to more than 100% for that plot. Net sum cannot exceed 100% for "Percent Covered" (this is similar behavior to what we have in place for jurisdiction.
 - [ ] ADDITIONAL FIELD: Beside "Cover Method (fmr Count Type)" drop-down, add new field with drop-downs for Basal Cover & Foliar Cover and label this new field as "Cover Type"
- [ ]  LABEL CHANGE: name the buttons to be "add transect" "add plot" instead of "add item"
 Each transect is a different colour for ease of viewing? if possible? (In relation to above point "auto-generate number in the "Sample Point I.D." when additional items are added for both Transect and Plot.")
- [ ]  FIELD BEHAVIOUR CHANGE: auto-generate number in the "Sample Point I.D." when additional items are added for both Transect and Plot (i.e. 1, 2, 3, 4, ...).
- [ ]  Phenology ... they will be held under an accordion titled "additional details" (that only shows up if selected by user)
Additional information:
- [ ]  Testing needed to ensure that user can't proceed when invalid fields entered (in lieu of warnings displayed to user when invalid fields entered)
- [ ]  Additional Ticket will be created to address workflow, record linking etc. after call with Crystal on morning of March 8th -ZSimon

**Form design fixes:**
- [ ] Basic information of polygon location, UTMs of specific transect collected down in form. 
  - [ ] Need Basic information to also have UTMs available on transect forms to supplement general location, people think in UTMs not lat/long (ticket for UTM in all other forms #607)
- [ ] Biocontrol collection form needs to be built, details & spreadsheet in ticket #608
 help text change for phenology under the bio treatment & bio efficacy monitoring (the monitoring form of the treatment), once the forms are more finalized after meeting on Tuesday, @mikeshasko to send spreadsheet to Susan to obtain help-text.
Workflow complex

**Comment by ZoeSimon** [comment]
@mikeshasko & @sdevalapurkar to work on and merge prior to User Testing on Wednesday March 10th.

**Comment by CrystalChadburn** [comment]
Need to add in these two while cleaning this up.

- (M) Need a solution for negative dispersal, and no negative values throughout all forms. 
- (H) Need to fix to prevent future dates (should only be able to pick today)
