### ISSUE TITLE
Plan my trip page: UI Component for choosing data to cache

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#60]
UI Component for choosing data to cache
- [x] Build UI for what elements a user should be able to choose when it comes to caching data for their trip
- [x] The choices the user makes are associated to the 'plan your trip' record
- [x] Refer to ticket #811
_Originally posted by @ZoeSimon in https://github.com/bcgov/invasivesbc/issues/57#issuecomment-704376306_

**Comment by micheal-w-wells** [comment]
my work bled into this one so i pulled this in and swapped out an iapp ticket
