### ISSUE TITLE
UTM in addition to Lat/Long on forms

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#607]
**Describe the Task**
Users want UTM coordinates in addition to Lat Long on ALL forms under the Basic Information Section.

**Comment by ZoeSimon** [comment]
@popkinj to complete some research first and then estimate ticket

**Comment by popkinj** [comment]
I think we can do this in the front end. This is a two step process
1. Find the UTM zone with the following equation: `(Math.floor((lon + 180) / 6) % 60) + 1;`
2. The use [proj4js](http://proj4js.org/) to calculate UTM coordinates
