### ISSUE TITLE
Plan my trip page: Fetching other peoples activities

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#61]
Fetching other peoples activities
- [x] User can also pull photos (optionally)
  - Created a new endpoint for specifically fetching media
- [x] Creation of a new API endpoint
  - Created a new endpoint for fetching activities based on some basic parameters (date range, type, subtype) and pagination (page, limit)
- [x] Write spatial query
  - Added a spatial search to the above endpoint, searches based on a provided polygon.
_Originally posted by @ZoeSimon in https://github.com/bcgov/invasivesbc/issues/57#issuecomment-704378642_

**Comment by micheal-w-wells** [comment]
first filter params:

- [x] type of activity
- [x] photos
- [x] date ranges

v2

- [x] spatial query


v3

- [ ] view offline form data

v4


- [ ] see photos on map or with form

**Comment by NickPhura** [comment]
Pushed some api/app changes.

App
- Updated the `useInasivesApi()` hook to include a new `getActivities` method that accepts a search criteria object.  Returns all activities that match.
  - This currently accepts a bounding box `bbox` parameter, but the api doesn't do anything with it yet.
  - It also accepts an 'include_media' parameter, which the api ignores for now.  I think we will have to move this out into its own call though, as the request size might get too big if the user gets 50 activities and they all have media.

Api
- Updated the request body of the `GET /activity` endpoint to the latest version (as in the App).
- Left a placeholder spot in `activity-queries.ts` for the spatial query portion, which is empty for now.

**Comment by ZoeSimon** [comment]
V3 & V4 captured in ticket #108
