### ISSUE TITLE
App boots on offline on ios / Public layout does not work

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#613]
**Describe the bug**
The Auth Layout / Public layout code to allow for people to work without getting booted does not work.

Set newLayout directly to public layout and it goes straight to access denied.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by micheal-w-wells** [comment]
@sdevalapurkar @NickPhura I solved some issues (network status not initialized ios and device not being recognized) but the issue of public layout not working persists.  I didn't write this part and could use a hand from the guys who put it together if you can take a look.

**Comment by micheal-w-wells** [comment]
@mikeshasko @ZoeSimon heads up Ipad is broken offline until we sort this one.  Had another look today and not seeing the solution just yet.

**Comment by sdevalapurkar** [comment]
https://github.com/bcgov/invasivesbc/pull/623
