### ISSUE TITLE
User-Friendlyness of the app

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#616]
In addition to making the "Plan My Trip" page more inuitive and user friendly, there needs to be a focus on making the form flow more user friendly (copying form data, clone form data, hitting continue button and just overall navigation from page to page). 

It was highlighted in our training session with Becky that the navigating when filling out forms isn't super clear where the user goes next, what the error messages on the banner are for, etc. 

- "It allowed me to copy form data without checking accuracy. Checking form accuracy should be automatic, not left up to the data enterer. The user should be trained to do "Check form for errors" first before "copy form data", we can work on making that more intuitive."
- "When I copy a form, where does it go and how do I find it? I selected another entry and paste form....is that the spot? So I've just duplicated two forms without checking that anything is completed properly."

**Comment by micheal-w-wells** [comment]
Covered by #689 and #586
