### ISSUE TITLE
Sandy's iPad testing issue

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#635]
I tested my iPad, outside as an effort to attempt something instead of nothing. 
I created a polygon, sort of, I had to activate my cell service to do so, I guess I should have created some tiles first???? Now what to do with it is a question. I think I wiped it out later. 

Regardless, what I have found on the iPad, or at least the one in my care is the following:
  1. When I am planning a trip, the map in the upper right appears to lay over top of the tools. The tools, save tiles set, become visible when I tap on the extreme edge of the map frame. They also become visible when I zoom out of the map, but only for a split second, then disappear again behind the map. 
  2. In the plan my trip screen, the blue bar seen on the desktop monitor right at the bottom of the page blocks the lower option such as Fetch and the Advanced option. 

Attached screenshot of iPad. 
iPad pro.

![Sandy ipad](https://user-images.githubusercontent.com/62561887/110873750-4aad4f80-8287-11eb-9198-085f23761ed2.png)

**Comment by micheal-w-wells** [comment]
this one can be closed because the page was rewritten - but it would still be a good idea to test the new stuff on this ipad.
