### ISSUE TITLE
iPADs for testing

### ISSUE THREAD

**Issue by ghost** [bcgov/invasivesbc#643]
Shasko iPAD devices

A2316 / iPAD AIr 4th Gen  / 64 gb / ios 14.4 / with stylus

A1709 / iPAD Pro 10.5" / 256 gb / ios 13.7 / with stylus

A1489 / iPAD Mini 2 / 16gb / ios 12.4.9 

A1395 / iPAD 10.5" / 16gb / ios 9.3.5  [ too old ]

**Comment by CrystalChadburn** [comment]
@micheal-w-wells  Do you still need this info in a ticket, or is there somewhere else to put it to close this ticket?
