### ISSUE TITLE
Lakes and Cities

### ISSUE THREAD

**Issue by ghost** [bcgov/invasivesbc#644]
Attached are 150 BC places to support the initial location options based on the user picking their destination from a dropdown.
An additional 7000 water bodies names are provided to support any aquatic related locationing or autofilling.

[https://app.zenhub.com/files/296689811/0a318189-8b89-41cf-a86e-eeb919e07565/download](https://app.zenhub.com/files/296689811/0a318189-8b89-41cf-a86e-eeb919e07565/download)

[https://app.zenhub.com/files/296689811/13da3a51-c35f-40bf-af3b-0016bce311d7/download](https://app.zenhub.com/files/296689811/13da3a51-c35f-40bf-af3b-0016bce311d7/download)

**Comment by CrystalChadburn** [comment]
@micheal-w-wells  we should discuss this as I don't think it would be necessary anymore if we can take the names from the layers?
