### ISSUE TITLE
Part II: Auto-complete Species Drop-down

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#645]
**Part II of ticket #251**
**Is your feature request related to a problem? Please describe.**
Currently the app brings you to the desired species just based on the first character. 

**Describe the solution you'd like**
The user wants to be brought to the species in drop-down if they start typing either the Scientific, Common name, or species Code for both Plants and Animals

- [X] MultiSelect Autocomplete Widget (from BioHub) _Completed in #251_
- [X] Single-Select Autocomplete Widget (modified) _Completed in #251_
- [ ] Get Autocomplete widgets working with x-code tables
- [ ] Implement Autocomplete across all forms (as default behavior or custom)
- [ ] Implement Species drop-down specifically, using the Autocomplete widget

**Additional Context**
- Get guidance from Nick on how to implement last 3 bullets.

**Comment by dogcomplex** [comment]
So, difficulty here isn't really any of those later points, but a persistant bug where validating the form gets you multiple "is not a string" validation errors on the field, despite (by all appearances) the value set in the autocomplete being a string (or whatever the type of the field should be).  Needs some magic-behavior deciphering there of the various layers of openapi/validation/react autocomplete behavior
