### ISSUE TITLE
Research ticket: Geo-referenced pdf map generated from app

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#65]
**Describe the Task**
Users need the ability to generate a geo-referenced pdf map with their selected layers directly from the application. Research the ability/options for implementing this feature.

Thoughts:
- Generate the PDF front end
- Capture extent
- Server uses GDAL to generate pdf

**Comment by popkinj** [comment]
I believe this product is possible.

**Requirements**
- A NodeJS service that has access to the [GDAL](https://gdal.org/) tool set.
- A modern browser that has [Screenshot API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture) capabilities.

**Considerations**
- The geographical accuracy is unknown
- Results may differ depending on user's browser, Operating system and configuration.

**Comment by ZoeSimon** [comment]
@mikeshasko Please review and close
