### ISSUE TITLE
Version 1 of InvasivesBC app theme

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#66]
**Describe the Task**
Researching/exploring what's capable in terms of styling with form library. Theming first, layout later. 

**First things to look at include:**
- [x] Implementing BC gov color scheme
- [x] Light theme

**Comment by micheal-w-wells** [comment]
We're using material-ui to theme, see below in App.tsx it can be done by overriding the palette colours and I'll paste a link to the doc also.  Note that there's also a provision for a 'dark mode'.

**Comment by micheal-w-wells** [comment]
https://material-ui.com/customization/palette/

**Comment by micheal-w-wells** [comment]
https://github.com/bcgov/invasivesbc/blob/a5e92c4477194d41f9e0a4f16671168c08fb8f7c/app/src/App.tsx#L12

**Comment by victorchong** [comment]
Found this VERY cool colour picking tool from the Material folks. the best thing is that it doesn't just let you choose colours: it generates the Palette object for you!

https://material.io/resources/color/#!/?view.left=0&view.right=0&primary.color=3F51B5&secondary.color=F44336

**Comment by victorchong** [comment]
Found this **VERY** cool colour picking tool from the Material folks. the best thing is that it doesn't just let you choose colours: it generates the Palette object for you!

https://material.io/resources/color/#!/?view.left=0&view.right=0&primary.color=3F51B5&secondary.color=F44336

**Comment by victorchong** [comment]
Colour palette is from the BC Government's "[Design Guidelines for the B.C. Visual Identity Program](https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/bc-visual-identity/design-guidelines#:~:text=The%20province's%20visual%20identity%20program,Adobe%20Myriad%20and%20BC%20Sans).)".

**Comment by victorchong** [comment]
Colour palette is from the BC Government's "[Design Guidelines for the B.C. Visual Identity Program](https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/bc-visual-identity/design-guidelines#:~:text=The%20province's%20visual%20identity%20program,Adobe%20Myriad%20and%20BC%20Sans).".

**Comment by victorchong** [comment]
Colour palette is from the BC Government's "[Design Guidelines for the B.C. Visual Identity Program](https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/bc-visual-identity/design-guidelines#:~:text=The%20province's%20visual%20identity%20program,Adobe%20Myriad%20and%20BC%20Sans)".

**Comment by victorchong** [comment]
Here are the B.C. Visual Identify [colours](https://material.io/resources/color/#!/?view.left=0&view.right=1&primary.color=234075&secondary.color=e2a928) within the Material Color Tool.

**Comment by victorc-bcgov** [comment]
Found this **VERY** cool colour picking tool from the Material folks. the best thing is that it doesn't just let you choose colours: it generates a Palette object for you (use the Export feature)!

https://material.io/resources/color/#!/?view.left=0&view.right=0&primary.color=3F51B5&secondary.color=F44336Colour palette is from the BC Government's "[Design Guidelines for the B.C. Visual Identity Program](https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/bc-visual-identity/design-guidelines#:~:text=The%20province's%20visual%20identity%20program,Adobe%20Myriad%20and%20BC%20Sans)".

Here are the B.C. Visual Identify [colours](https://material.io/resources/color/#!/?view.left=0&view.right=1&primary.color=234075&secondary.color=e2a928) within the Material Color Tool.

**Comment by victorc-bcgov** [comment]
@micheal-w-wells, can you please try adding this snippet to the [App.tsx](https://github.com/bcgov/invasivesbc/blob/a5e92c4477194d41f9e0a4f16671168c08fb8f7c/app/src/App.tsx) file? Here is the entire definition for **`const theme`**:

```
const theme = createMuiTheme({
  palette: {
    primary: {
      light: '#5469a4',
      main: '#223f75',   // BC ID: corporate blue
      dark: '#001949',
      contrastText: '#ffffff'
    },
    secondary: {
      light: '#ffd95e',
      main: '#e3a82b',   // BC ID: corporate gold
      dark: '#ad7900',
      contrastText: '#000000'
    }
  },
  overrides: {
    MuiCircularProgress: {
      root: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        height: '60px !important',
        width: '60px !important',
        marginLeft: '-30px',
        marginTop: '-30px'
      }
    },
    MuiContainer: {
      root: {
        maxWidth: 'xl'
      }
    }
  }
});
```

Note: the **`palette`** stanza is the new code addition.

**Comment by micheal-w-wells** [comment]
stuff to carry forward in a v2 ticket: 
- [ ] Dark theme

**Comment by micheal-w-wells** [comment]
stuff for a dev to pickup later:
- [ ] Ability to have 2 columns or 3 (dependent on iPad users)
- [ ] Boxes instead of lines
