### ISSUE TITLE
Form dropdowns - content lists only showing the first 50 or so values

### ISSUE THREAD

**Issue by ghost** [bcgov/invasivesbc#666]
**Describe the bug**
Form dropdowns - content lists only showing the first 50 or so values.
Ie the species / jur / agency lists truncate.

**To Reproduce**
Dropdown form lists that have more than 50 records

**Comment by ZoeSimon** [comment]
Just a gentle reminder @mikeshasko , the Critical Label is only used for "dev task" specific tasks as agreed to in our DOD/DOR, this is a circumstance where you would just assign the "bug" label and then put it at the top of the Next Sprint pipeline if you want it tackled before other tasks.
