### ISSUE TITLE
Offline Button to be Disabled at Higher Scales.

### ISSUE THREAD

**Issue by popkinj** [bcgov/invasivesbc#676]
This was previously done with the offline buttons that came with the plugin.

**Comment by micheal-w-wells** [comment]
@popkinj let's talk about this one, I think we've got some overlap with the other planning/caching work.

**Comment by popkinj** [comment]
Agreed @micheal-w-wells

**Comment by CrystalChadburn** [comment]
You probably know this but the goal of this was to figure out at what scale users definitely can't cache records, and avoid them having the option to even try (and therefore hanging up their browser).
