### ISSUE TITLE
First time user popups

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#689]
The InvasivesBC system would benefit from some 'first time user' type pop ups (or perhaps a hideable sidebar) that would show instructional content related to the task at hand that is more comprehensive than what is available/suitable in help text.  The user should be able to tick a box saying "don't show me this next time" if they would like.  

This issue will cover the initial development of this feature, with subsequent issues to cover the different use cases we see fit.  Example:

How to use the Plan Trip Page, or where to go after caching data, or tips/gotchas for using the copy/paste form data items.

**Comment by CrystalChadburn** [comment]
@micheal-w-wells  do you think this is still needed?  I think the how to page is enough?
