### ISSUE TITLE
Specific Use Codes on IAPP Mapping

### ISSUE THREAD

**Issue by dogcomplex** [bcgov/invasivesbc#691]
Currently the specific_use_code field on IAPP, taken from SpecificUse on the IAPP Sites CVS, does not map correctly to any of our Specific Use codes in the database (codes used for Activities etc).  We need to map these to our new codes in the IAPP Migrator, but I have no idea what they correspond to.

Current values in IAPP Sites CSV "SpecificUse" field::
RA
GR
RT
NH
SS
YW
WB
WP
PL
NS
WE
TL

Currently our Specific Use Codes table only has:
NO (None)
NA (unknown) 
GP (Gravel Pit)

(Okay, might have started this issue before looking up the database table and seeing how sparse it is.  Mystery solved: just gotta fill in the table!)

**Comment by CrystalChadburn** [comment]
@dogcomplex is this all sorted out now?  Does it need a ticket still or should I close this?

**Comment by dogcomplex** [comment]
Looked into the code table with this and compared to our data: at the current moment we have mappings for the following:

```
 code_name |      code_description      
-----------+----------------------------
 BS        | Burn scar
 CL        | Cultivated land
 CP        | Community pasture
 GP        | Gravel pit
 HW        | Numbered highway
 IS        | Industrial site
 MI        | Mine site
 MT        | Mine tailings
 NA        | unknown
 NO        | None
 NS        | No-spray zone
 PF        | Within PFZ
 PL        | Parking lot
 QU        | Quarry
 RA        | Rest area
 RC        | Research site
 RS        | Rec site/trail
 RV        | Reservoir
 RW        | Railway
 SS        | Sensitive site
 TL        | Transmission line
 TS        | Transfer station/landfill
 WB        | Within PFZ - water body
 WE        | Within PFZ - well
 YD        | Yard / ditching waste dump
 
 ```
 
 Which leaves just the following unknown codes from IAPP which we don't have a corresponding code in the new system for.  @mikeshasko or @CrystalChadburn, if either of you know which of the above codes these could be mapped/renamed to, I can add that to the IAPP loader and port them over.  We could also add new codes with descriptions for them.
 
 ```
 GR
RT
NH
YW
WP
```

Sidenote: how should we treat blank rows where IAPP had no specific_use code?  "NA"? "NO"?  Just leave blank in our own system?

**Comment by ghost** [comment]
Warren – something has gone wrong with the SiteList specifically with the “Specific Use” variable.

The file provided only includes the 5  values ( GR / RT / / NH / YW / WP) which ARE NOT any of the IAPP codes.

The site.csv also doesn’t include any of the actual IAPP specific use code so somewhere along in my compilation, I’ve lost the species use codes.


At this time, I can re-create a new version of the original site list I provided with the corrected specific code values and you can replace the site table.

Alternatively I could provide a completely new cut of the IAPP data but then you’d have to replace all the IAPP related tables.

IAPP sites with blank specific use codes should be “NA”

**Comment by ghost** [comment]
@dogcomplex @CrystalChadburn 

IGNORE my last comment...

Upon review of the IAPP vs Invasive Specific Use codes the truth was uncovered.

When the project started, the InvasivesBC list of Specific Use codes was overhauled. Many additional rows were added and the 2 letter codes were modified to make more logical sense. As a result, 5 IAPP 2-letter codes where changed.

Where the IAPP code is blank/null, InvasivesBC should populate the Specific Use code with "NO" [none]

This is the "mapping table"


![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/f9360383-ed39-4515-9e1c-055947c90cea)
