### ISSUE TITLE
Fixes and additions required for caching IAPP data by date range

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#701]
**When caching IAPP records using the date range filter, it is currently pulling from pointing to when the record was uploaded to the new system**

What the user wants to see in plan trip:

- [x] Enable users to pull IAPP data from site created date 
- [x] Enable users to pull IAPP sites with treatments within a date range
- [x] Enable users to pull IAPP sites with surveys within a date range

What needs to happen:
- [x] create a view called iapp site summary (if it doesn't already exist)
Take a look at how the other views parse json, you'll need that to get the following data from point_of_interest_incoming_data.point_of_interest_payload:
- [x] add a computed  column for site created date
- [x] add a computed column for earliest mechanical treatment
- [x] add a computed column for most recent mechanical treatment
- [x] add a computed column for earliest chemical treatment
- [x] add a computed column for most recent chemical treatment
- [x] add a computed column for earliest biological control treatment
- [x] add a computed column for most recent biological control treatment
- [x] add a computed column for earliest biological dispersal
- [x] add a computed column for most recent biological dispersal
- [x] add a computed column for earliest survey
- [x] add a computed column for most recent survey
- [x] add a computed column for earliest efficacy monitoring record
- [x] add a computed column for most recent efficacy monitoring record

API & useInvasivesAPI changes:
- [x] Update the point of interest search filter to include those optional date fields
- [x] update API to use these filters.

**Comment by micheal-w-wells** [comment]
@dogcomplex @CrystalChadburn couldn't find site created date in the data - can @dogcomplex & @mikeshasko confirm it was loaded?  maybe we're blind.  the date that is there is just when the record was loaded in our system.
