### ISSUE TITLE
Create rules and functionality for multiple records in an area to interact spatially for reporting (instead of linking records)

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#706]
As an InvasivesBC user, I need to be able to enter an independent record (observation, treatment, biocontrol dispersal, etc) without having to choose historical records to link it to.  Then I need the system to be able to accurately overlay and do calculations so that when we extract data via metabase or other ways, it doesn't duplicate any areas where multiple observations occur, and it doesn't give you area post-treatment etc.  

- @CrystalChadburn  will draft out the "rules" that we need to solve with help from the SMEs.
- @micheal-w-wells  please add details to this with the right techy words and checkboxes

**Comment by micheal-w-wells** [comment]
Hey Jamie - for this ticket just worry about this:

- [ ] Make a view in postgres that lists observation ids, the original activity geo, and (in a separate column) the geo the union geo it is a part of, and that union geo's id.
- [ ] Take into account negative observations.  Chat before we start this one.
- [ ] take into account multiple species.

That will allow us to either group by activity / observation id, or group by the union geo id for reporting total by species etc later down the road, or to provide a featurecollection of just the union geos (without duplicates, grouped by union geo id).
