### ISSUE TITLE
IAPP Migration: Get app to pull site locations based on user input

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#71]
**Describe the Task**
- [x] Get app to pull site locations based on user input

**Comment by micheal-w-wells** [comment]
@mikeshasko 
The front-end and API for this (fetching & caching with filters) is done.  

What's remaining for "v1 IAPP sites" or "Points of Interest v1 with type IAPP Site" in InvasivesBC now is:

- [x] Get the IAPP sites into ```point_of_interest_incoming_data```, probably by taking the csv and turning it into json for POST's with at least a dummy photo.

- [x] Choose an (interim) marker for IAPP sites/point of interest and show some of the attributes in a pop up, and show the photo(s) somewhere.  If the popup doesn't fit everything we can do something similar to the reference activities (have a listview of records).

Can be another ticket:

- [ ] Get the IAPP photos out of the prod db and have code ready to put them through the API.  Important to get this one out of way so we aren't fumbling near go-live and can say for real that the IAPP migration stuff is behind us (earlier).
