### ISSUE TITLE
KML upload for caching records.

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#719]
- [ ] User needs to be able to upload a kml and excel file of InvasivesBC records to cache 
- [ ] User needs to be able to upload a kml on plan my trip page of IAPP sites that will be cached for offline access, including the metadata attached to the sites.

**Comment by micheal-w-wells** [comment]
This is mostly done - needs an update for multi trip & a decision @CrystalChadburn of whether or not to change the behaviour from:
- A) taking the first shape in the kml (least work)
- B) or for including all of them (maybe complicated)
- C) or a buffered polygon containing all of them (slightly more work than A, but not that bad).

**Comment by ghost** [comment]
Test KMLs

Maine Island point and various simple polygon types.

Vargas Island complex polygon with donuts

**Comment by micheal-w-wells** [comment]
duplicate
