### ISSUE TITLE
Ability to enter a record in a location where you haven't cached maps/data

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#728]
- [x] allow users to enter a treatment or observation (or any form) by entering a UTM or LAT LONG only, instead of entering the location on the map.

Could be web only if that is easier.  Users will need this if they haven't cached the maps but they have the UTM or lat/long from their GPS.

**Comment by CrystalChadburn** [comment]
@micheal-w-wells  is this still an issue or will mobile users always have a base map now that they can make a record onto using the map in the form even if they didn't cache that particular location.

**Comment by micheal-w-wells** [comment]
I think we're good on this one - we just need to do some field testing.
