### ISSUE TITLE
Part II: make drop down / ref data populate in API spec schema

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#73]
**Describe the Task**
- [X] * @mikeshasko has new and updated code tables that need to make it into the db

**Describe the task**
For the various InvasiveBC dropdowns and related attribute tables we wish to see the following code tables in their respective dropdowns with the default and sort orders in place.
- [ ] convert his tables into db migrations 

**Acceptance Criteria**
- [ ] pest_management_plan
- [ ] plant_life_stage_code
- [ ] animal_life_stage_code
- [ ] plant_health_code
- [ ] plant_seed_stage_code
- [ ] animal_behavior_code
- [ ] bioagent_maturity_status_code
- [ ] biological_agent_stage_code
- [ ] biological_agent_presence_code
- [ ] classified_area_code
- [ ] proposed_treatment_code
- [ ] observation_type_code
- [ ] observation_geometry_code
- [ ] specific_use_code
- [ ] aspect_code
- [ ] invasive_plant_density_code
- [ ] slope_code
- [ ] invasive_plant_distribution_code
- [ ] mechanical_disposal_code
- [ ] mechanical_method_code
- [ ] root_removal_code
- [ ] soil_disturbance_code
- [ ] treatment_issues_code
- [ ] soil_texture_code
- [ ] chemical_method_code
- [ ] efficacy_code
- [ ] liquid_herbicide_code
- [ ] granule_herbicide_code
- [ ] invasive_plant_code
- [ ] invasive_animal_code
- [ ] biological_agent_code
- [ ] invasive_species_agency_code
- [ ] jurisdiction_code
- [ ] pesticide_employee_certificate_code
- [ ] pesticide_employer_code

Steps:
- [X] Step one: make migrations and seeds work with Roland's structure
- [ ] Step two: create a mechanism to read the seed data from csv files
- [ ] Step three: convert Mike Shasko's spreadsheets into csv files (30 files)

(Step 2 & 3 will be completed in ticket #119 )

**Comment by ghost** [comment]
Can I structure them to support DB migrations ?

**Comment by micheal-w-wells** [comment]
after the first one probably yes, we're gonna roll with @rstens structure for the first one then you can take a look at how @anissa-agahchen seeds it with data.

**Comment by anissa-agahchen** [comment]
Mechanism to read seed data:  

* explored npm module knex-csv-seeder .... a dead end
* working on the following:  read a csv file, parse it, store as an array (in progress)

**Comment by rstens** [comment]
What about using knex.raw and using the postgres csv loader: https://www.postgresqltutorial.com/import-csv-file-into-posgresql-table/
