### ISSUE TITLE
Users can only enter records for employer (multiple) they have access for

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#734]
As a user I will only be given the options in the drop down for the employer field in all forms for those that I have user access linked to.

action once ticket #470 is complete.

**Comment by sam-warren** [comment]
Had to re-think current implementation of users seeing only roles they have access to for security and efficiency purposes. Working on designing a better solution, half-implemented and in testing. Approx. 4hrs left on this one.

**Comment by sam-warren** [comment]
Not yet started but not difficult. Just need to inject form data with user's employers and agencies, which are available from the authStateContext. Approx 3 hrs for full implementation and testing
