### ISSUE TITLE
Discuss Spatial caching on app

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#74]
**Describe the Task**
Discuss Spatial caching on app

**Comment by micheal-w-wells** [comment]
* overall plan is to make a service that allows a person to check for intersections between a list of layers kept in sync with the warehouse, and the geojson input
* this service should be shared with all SEISM projects
* plan on device is to cache layers in geojson and images, which will be served up by geoserver when we can't pull WMS from the warehouse directly
