### ISSUE TITLE
Stuff we can do without IDIR

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#778]
- [x] make sure can stand app up locally
- [x] if have a mac - get set up to run in simulator
- [x] see if BCEID login works - self register
- [ ] set up dev keycloak token (so devs don't have to login every time app launches).
- [x] start the layer picker
- [ ] batch loader

**Comment by hpertaia** [comment]
Logging in with a basic BCeID account worked.

**Comment by micheal-w-wells** [comment]
batch loader is already another ticket,  set up dev keycloak token (so devs don't have to login every time app launches) can be another
