### ISSUE TITLE
Autofill certain fields with the users data associated with their log in access

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#813]
MUST HAVE:
- [x] Pesticide Applicator Certificate (PAC) should be autofilled based on the information attached to their account they submitted when requesting access.   BUT you must be able to override it if need be (ie when someone else is spraying and another person is logged in entering the record).
- [x] Surveyor, or treatment person name should be suggested as the first name chosen on all records.
- [x] user should only have the service licence(s) attached to their user access details as options to choose from for this field.
- [x] user should only have the employer(s) attached to their access details as options to choose from for this field.

This is required for both the terrestrial and aquatic chemical treatment forms.

- [x] NOTE: All Ministry people have service license as "OOOOO" but they may not know this.  It's because gov people don't need a service license.  So anyone given access with any bc gov ministry employer should autofill as 00000 for service license (BUT THEY STILL NEED A PAC NUMBER).

**Comment by sam-warren** [comment]
Easy one - just need to create an auto-fill and pass the user's current info in the authStateContext to the validator in record tables for a custom validator to pick it up and autofill. Approx. 2hrs for full implementation and testing.
