### ISSUE TITLE
IAPP site created date missing in point of interest data

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#818]
Related to #701 , need to reload data and include site created date.  @dogcomplex

**Comment by dogcomplex** [comment]
So, the excel docs provided by @mikeshasko don't have created dates for IAPP POIs, but they do have survey_date fields.  Picking the earliest survey_date would probably be sufficient there.  Though if we get a better look at all the IAPP data perhaps there's an explicit legacy created_date

**Comment by micheal-w-wells** [comment]
hey @dogcomplex let me and @hpertaia know when this data is loaded again so we can update the iapp_summary views and get that part of the plan page filters working

**Comment by micheal-w-wells** [comment]
@dogcomplex can we do this one today?
