### ISSUE TITLE
Openshift gold phase 2 

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#836]
- follow up to ticket #835 (open shift gold phase 1)
- @micheal-w-wells outline what is required for phase 2.  Here is what your email to me said:

Basically moving to Gold (from my understanding) means:

1.	Less downtime because they use silver as the guinea pigs
2.	Also comes with extra work because you need to have two instances of your app, along with provisions to switch between them in a disaster scenario.

Even if phase 1 meant we just got #1, that is still a win.  Phase 2 comes with benefit of essentially no downtime even if one data center gets nuked, however there’s a lot of work involved in getting the ‘failover’ stuff to work.

I’d make two tickets – “Openshift gold Phase 1” & “Openshift gold Phase 2”, scope is pretty clear for phase 1, phase 2 needs more investigation/planning.

**Comment by micheal-w-wells** [comment]
I think the only downtime we've had in silver over 2 years has just been when idir or bcied have issues very briefly, which gold wouldn't save us from anyway.  I think we should roll with silver for a year and evaluate the costs/benefits of moving to gold and park this for now.
