### ISSUE TITLE
Inaccurate Timestamps for Activities in the Database

### ISSUE THREAD

**Issue by popkinj** [bcgov/invasivesbc#840]
- @dogcomplex  please confirm if this is true, and fix it if needed.

**Inaccurate Timestamps for Activities in the Database**
All activity entries have the same minute and second entries _(30:08)_:

|             activity_id              |  created_timestamp  |
|--------------------------------------|---------------------|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-09 19:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-10 16:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-15 22:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-09 12:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-13 14:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-10 09:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-15 15:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-11 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-03 02:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-15 08:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-10 02:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-17 16:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-06-29 07:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-17 23:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-17 09:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-17 02:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-16 19:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-16 12:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-07 18:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-17 23:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-06-29 14:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-17 16:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-17 16:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-17 23:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-16 05:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-17 09:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-15 22:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-17 23:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-06-30 18:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-18 06:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-13 21:30:08|
| d3d3a89c-4e11-4dd2-848e-aea53c32b672 | 2021-07-15 08:30:08|

**Reproduce**

Within the database execute the following SQL:

```sql
select
  activity_id,
  created_timestamp
from
  invasivesbc.activity_incoming_data
where
  activity_id = 'd3d3a89c-4e11-4dd2-848e-aea53c32b672'
limit
  70
;
```

**Comment by dogcomplex** [comment]
Soooo, this is actually exactly as intended as far as I can tell.  Those are all the same activity, just different softdelete versions!  When you look at all activities, they all have different accurate timestamps:


```
select
  activity_id,
  created_timestamp,
  received_timestamp
from
  invasivesbc.activity_incoming_data
WHERE 
   deleted_timestamp IS NULL
order by
	created_timestamp DESC
;
```
