### ISSUE TITLE
Create a public facing map view for observations only

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#843]
- [x] should show all observation records 
Moving these two out to the filtering ticket:
~~- [ ] (sortable and filterable by date, species area and jurisdiction)~~
~~- [ ]  with the observer name(s), agency and employer fields hidden.~~
- [x]  no idir, bceID or access into InvasivesBC will be required - this will be accessed via a website.
- related to #867 
- [x] good for the public to be able to use the layer picker but they can not open the record to see details, and should not be able to make a record etc. so will need to hide those buttons.

**Comment by micheal-w-wells** [comment]
The "main" task is done, going to move filtering out of this task.
