### ISSUE TITLE
Invasive plant form fixes 

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#856]
- [x] move "check form for errors" and "copy form data" buttons to the bottom of the form (FYI we will be adding 1-2 additional buttons as well called "save form" and possibly "submit form" TBD)

**Comment by hpertaia** [comment]
There is no simple way to change two headings there. Those are bound to our objects and after removing the title from either one, it would show the name of the object instead. An example would be: after removing the "Terrestrial Plant Information" title, it would show activity_subtype_data instead.
