### ISSUE TITLE
IAPP species on site

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#867]
EDIT:  Breaking this one up as much is done, making remaining work obvious.

- [x] do ticket #843   first
- [x] ensure IAPP points of interest can be viewed with the species code as labels on a public facing map accessed via a website
Edit see comment below for the ticket for this task:
~~- [ ] When a user clicks on an iapp point of interest, the following information shows in a pop up: species (one or more), date created, jurisdiction(s), area in most recent survey attached to site, ever treated or not (no details of treatment except whether it was mechanical, chemical or biological).~~
- [x] ensure public users (without access) cannot open the records.

**Comment by micheal-w-wells** [comment]
IAPP map on click behaviour:

- [ ] When a user clicks on an iapp point of interest, the following information shows in a pop up: species (one or more), date created, jurisdiction(s), area in most recent survey attached to site, ever treated or not (no details of treatment except whether it was mechanical, chemical or biological).
