### ISSUE TITLE
Bug:  DB/API-level Activity Duplicates

### ISSUE THREAD

**Issue by dogcomplex** [bcgov/invasivesbc#894]
Somehow the API / DB is not respecting transactions when it soft deletes and it's possible to create multiple copies of an activity with the same id and deleted_timestamp set to NULL

This can be imperfectly replicated by messing around on an activity form and causing a lot of short-burst db updates at once.  An additional problem is those update requests arent being throttled sufficiently in the first place - though the API should be smart enough to treat them correctly regardless.

**Comment by micheal-w-wells** [comment]
tested and fixed in #1238 and #1243
