### ISSUE TITLE
IAPP content for magnifying glass pop up

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#971]
This ticket includes both the initial click to show a summary of IAPP data.... 

Hover over or click marker for Cached IAPP sites 
- [x] Site I.D. (not survey or treatment ID, SITE ID).
- [x] species (using the common name)
- [x] Jurisdiction - use what came with the point of interest / Iapp import

- [ ] users can click on an individual IAPP record (link select tool with this tool?) to see the details of it.
**** this to be done in #1332

**Comment by micheal-w-wells** [comment]
for activities: 

- [x] species - two letter codes & full name
- [x] area
- [x] remove name, ownership, agency
- [x] jurisdiction
- [x] record type (not system code)
