### ISSUE TITLE
Mechanical and chemical treatment form edits

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#998]
Please make the following edits in the Terrestrial and aquatic mechanical treatment forms:

- [x] remove the well ID and well proximity fields
- [x] under mechanical treatment information: add a new mandatory numerical field called "Treated Area (m2)" after invasive plant and before mechanical method
- [x] add a new mandatory field called "Disposed material" and allow users to choose either "number of plants" or "weight" (kg) and then enter a number.
- [x] build the functionality so users can add multiple invasive plants to a record (similar to chemical).  Each "add item" should include the invasive plant, mechanical method, area treated, disposal method and disposed material (kg) fields.
- [x] Under mechanical treatment information, make sure the first field is invasive plant, (then treated area, and the disposal related fields)

Additional aquatic chemical treatment form edits:
- [x] Move the check box for the "tank mix" up as the first field under the herbicide heading, and only show the "tank volume" field if the tank mix check box is chosen. (similar to what we just discussed for terrestrial chemical form

**Comment by dogcomplex** [comment]
Note:  will need to modify src/utils/addActivity.js populateSpeciesArrays() if the position of species data is changed in the schema (e.g. by adding multiple species here instead of just one)

**Comment by CrystalChadburn** [comment]
@hpertaia  this one is ready for your action now please.
